// Catalogue d'aliments et de recettes. Données PURES, sans dépendance serveur.
//
// POURQUOI UN CATALOGUE ÉCRIT À LA MAIN. Les recettes étaient écrites par un
// modèle de langage à chaque clic. Ça coûtait un centime par régénération, ce
// qui n'est rien pris isolément et beaucoup rapporté au nombre de clients,
// mais surtout ça produisait des macros INVENTÉES : le modèle annonçait
// « 620 kcal, 42 g de protéines » sans jamais les calculer depuis les
// quantités qu'il venait d'écrire. Ici, les macros sont la SOMME des
// ingrédients, et les quantités sont ajustées pour atteindre la cible du jour.
// C'est moins spectaculaire à lire dans un prompt, et c'est juste.
//
// Le catalogue se veut large plutôt que profond : beaucoup de bases
// différentes (céréales, légumineuses, poissons, viandes, végétal), peu de
// variantes d'une même base. C'est la mise à l'échelle qui fabrique la
// diversité réelle, puisqu'une même recette sert un objectif de 1 800 kcal
// comme un objectif de 3 200 kcal.

import type { LocalText } from "@/lib/i18n";
/** Allergènes du questionnaire. Mêmes étiquettes que `lib/nutrition.ts`. */
export type Allergene = "gluten" | "lactose" | "nuts" | "egg" | "fish" | "shell" | "soy";

/**
 * Niveau de régime le plus contraignant qu'un aliment impose.
 * L'ordre compte : `vegetal` passe partout, `porc` nulle part sauf omnivore.
 */
export type Regime = "vegetal" | "oeuf_lait" | "poisson" | "viande" | "porc";

/**
 * Rayon de magasin. Il vit sur l'aliment et non dans une expression régulière
 * appliquée à son nom : une liste de courses qui range « lait de coco » au
 * rayon crémerie parce que le mot « lait » y figure fait perdre confiance dans
 * tout le reste de la liste.
 */
export type Rayon = "fl" | "vp" | "cr" | "es" | "lc";

export const RAYON_LABEL: Record<Rayon, LocalText> = {
  fl: { fr: "Fruits & légumes", en: "Fruit & vegetables" },
  vp: { fr: "Viandes & poissons", en: "Meat & fish" },
  cr: { fr: "Crémerie & frais", en: "Dairy & chilled" },
  es: { fr: "Épicerie sèche", en: "Dry goods" },
  lc: { fr: "Condiments & liquides", en: "Condiments & drinks" },
};

/** Ordre d'affichage des rayons, celui d'un parcours de magasin. */
export const RAYON_ORDRE: readonly Rayon[] = ["fl", "vp", "cr", "es", "lc"];

export interface Food {
  nom: string;
  /** Pour 100 g (ou 100 ml pour les liquides). */
  kcal: number;
  p: number;
  c: number;
  f: number;
  allerg?: Allergene[];
  regime: Regime;
  /** Coût relatif : 1 économique, 2 courant, 3 cher. */
  cout: 1 | 2 | 3;
  /** Unité affichée. Vide = à la pièce. */
  unite?: "g" | "ml";
  /** Masse d'une pièce, en grammes (œuf 55 g). Affiche « 2 œufs ». */
  piece?: number;
  /** Libellé singulier / pluriel pour les aliments à la pièce. */
  pieceLabel?: [string, string];
  /** Étiquettes de refus fin : « boeuf », « porc », « alcool ». */
  tags?: string[];
  /** Rayon du magasin, pour ranger la liste de courses. */
  rayon: Rayon;
}

/**
 * Table des aliments. Macros pour 100 g, valeurs usuelles de tables de
 * composition (Ciqual / USDA), arrondies. Ce sont des ordres de grandeur de
 * cuisine, pas de laboratoire : c'est le bon niveau de précision pour une
 * assiette pesée à la louche.
 */
export const FOODS: Record<string, Food> = {
  // ───────────────────────────────────────────────────────────── protéines
  poulet: { nom: "Blanc de poulet", kcal: 110, p: 23, c: 0, f: 2, regime: "viande", cout: 2, unite: "g", rayon: "vp" },
  dinde: { nom: "Escalope de dinde", kcal: 105, p: 24, c: 0, f: 1.5, regime: "viande", cout: 2, unite: "g", rayon: "vp" },
  boeuf: { nom: "Bœuf haché 5 %", kcal: 140, p: 21, c: 0, f: 5, regime: "viande", cout: 3, unite: "g", tags: ["boeuf"], rayon: "vp" },
  porc: { nom: "Filet mignon de porc", kcal: 145, p: 22, c: 0, f: 6, regime: "porc", cout: 2, unite: "g", tags: ["porc"], rayon: "vp" },
  jambon: { nom: "Jambon blanc", kcal: 110, p: 20, c: 1, f: 3, regime: "porc", cout: 2, unite: "g", tags: ["porc"], rayon: "vp" },
  saumon: { nom: "Pavé de saumon", kcal: 200, p: 20, c: 0, f: 13, allerg: ["fish"], regime: "poisson", cout: 3, unite: "g", rayon: "vp" },
  cabillaud: { nom: "Dos de cabillaud", kcal: 82, p: 18, c: 0, f: 0.7, allerg: ["fish"], regime: "poisson", cout: 3, unite: "g", rayon: "vp" },
  thon: { nom: "Thon au naturel", kcal: 110, p: 25, c: 0, f: 1, allerg: ["fish"], regime: "poisson", cout: 1, unite: "g", rayon: "es" },
  sardines: { nom: "Sardines à l'huile égouttées", kcal: 210, p: 25, c: 0, f: 12, allerg: ["fish"], regime: "poisson", cout: 1, unite: "g", rayon: "es" },
  crevettes: { nom: "Crevettes décortiquées", kcal: 85, p: 20, c: 0.5, f: 0.5, allerg: ["shell"], regime: "poisson", cout: 3, unite: "g", rayon: "vp" },
  oeuf: { nom: "Œuf", kcal: 143, p: 13, c: 0.7, f: 10, allerg: ["egg"], regime: "oeuf_lait", cout: 1, piece: 55, pieceLabel: ["œuf", "œufs"], rayon: "cr" },
  skyr: { nom: "Skyr nature", kcal: 60, p: 11, c: 4, f: 0.2, allerg: ["lactose"], regime: "oeuf_lait", cout: 2, unite: "g", rayon: "cr" },
  fromage_blanc: { nom: "Fromage blanc 0 %", kcal: 47, p: 8, c: 4, f: 0.2, allerg: ["lactose"], regime: "oeuf_lait", cout: 1, unite: "g", rayon: "cr" },
  yaourt_grec: { nom: "Yaourt grec", kcal: 97, p: 9, c: 4, f: 5, allerg: ["lactose"], regime: "oeuf_lait", cout: 2, unite: "g", rayon: "cr" },
  cottage: { nom: "Cottage cheese", kcal: 98, p: 11, c: 3, f: 4.3, allerg: ["lactose"], regime: "oeuf_lait", cout: 2, unite: "g", rayon: "cr" },
  mozzarella: { nom: "Mozzarella", kcal: 250, p: 18, c: 1, f: 19, allerg: ["lactose"], regime: "oeuf_lait", cout: 2, unite: "g", rayon: "cr" },
  feta: { nom: "Feta", kcal: 264, p: 14, c: 4, f: 21, allerg: ["lactose"], regime: "oeuf_lait", cout: 2, unite: "g", rayon: "cr" },
  parmesan: { nom: "Parmesan râpé", kcal: 400, p: 33, c: 0, f: 28, allerg: ["lactose"], regime: "oeuf_lait", cout: 3, unite: "g", rayon: "cr" },
  whey: { nom: "Whey nature", kcal: 380, p: 78, c: 8, f: 5, allerg: ["lactose"], regime: "oeuf_lait", cout: 3, unite: "g", rayon: "es" },
  tofu: { nom: "Tofu ferme", kcal: 145, p: 16, c: 2, f: 9, allerg: ["soy"], regime: "vegetal", cout: 2, unite: "g", rayon: "cr" },
  tempeh: { nom: "Tempeh", kcal: 190, p: 19, c: 9, f: 11, allerg: ["soy"], regime: "vegetal", cout: 2, unite: "g", rayon: "cr" },
  seitan: { nom: "Seitan", kcal: 145, p: 25, c: 8, f: 2, allerg: ["gluten"], regime: "vegetal", cout: 2, unite: "g", rayon: "cr" },
  lentilles: { nom: "Lentilles cuites", kcal: 116, p: 9, c: 20, f: 0.4, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  lentilles_corail: { nom: "Lentilles corail sèches", kcal: 350, p: 24, c: 56, f: 1.5, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  pois_chiches: { nom: "Pois chiches cuits", kcal: 139, p: 8.9, c: 21, f: 2.6, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  haricots_rouges: { nom: "Haricots rouges cuits", kcal: 127, p: 8.7, c: 22, f: 0.5, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  edamame: { nom: "Edamame", kcal: 121, p: 12, c: 9, f: 5, allerg: ["soy"], regime: "vegetal", cout: 2, unite: "g", rayon: "es" },

  // ─────────────────────────────────────── protéines (élargissement du lot 4)
  poulet_cuisse: { nom: "Cuisse de poulet sans peau", kcal: 165, p: 20, c: 0, f: 9, regime: "viande", cout: 1, unite: "g", rayon: "vp" },
  dinde_hachee: { nom: "Dinde hachée", kcal: 150, p: 20, c: 0, f: 8, regime: "viande", cout: 2, unite: "g", rayon: "vp" },
  steak_hache: { nom: "Steak haché 15 %", kcal: 220, p: 20, c: 0, f: 15, regime: "viande", cout: 2, unite: "g", tags: ["boeuf"], rayon: "vp" },
  saucisse_volaille: { nom: "Saucisse de volaille", kcal: 220, p: 16, c: 2, f: 16, regime: "viande", cout: 2, unite: "g", rayon: "vp" },
  lardons: { nom: "Lardons fumés", kcal: 250, p: 17, c: 0.5, f: 20, regime: "porc", cout: 2, unite: "g", tags: ["porc"], rayon: "vp" },
  maquereau: { nom: "Filet de maquereau", kcal: 205, p: 19, c: 0, f: 14, allerg: ["fish"], regime: "poisson", cout: 1, unite: "g", rayon: "vp" },
  truite: { nom: "Filet de truite", kcal: 148, p: 20, c: 0, f: 7, allerg: ["fish"], regime: "poisson", cout: 3, unite: "g", rayon: "vp" },
  colin: { nom: "Dos de colin", kcal: 80, p: 17, c: 0, f: 1, allerg: ["fish"], regime: "poisson", cout: 2, unite: "g", rayon: "vp" },
  saumon_fume: { nom: "Saumon fumé", kcal: 180, p: 23, c: 0, f: 10, allerg: ["fish"], regime: "poisson", cout: 3, unite: "g", rayon: "vp" },
  moules: { nom: "Moules cuites", kcal: 86, p: 12, c: 4, f: 2, allerg: ["shell"], regime: "poisson", cout: 2, unite: "g", rayon: "vp" },
  ricotta: { nom: "Ricotta", kcal: 150, p: 11, c: 3, f: 10, allerg: ["lactose"], regime: "oeuf_lait", cout: 2, unite: "g", rayon: "cr" },
  chevre: { nom: "Fromage de chèvre frais", kcal: 270, p: 18, c: 2, f: 21, allerg: ["lactose"], regime: "oeuf_lait", cout: 2, unite: "g", rayon: "cr" },
  emmental: { nom: "Emmental râpé", kcal: 380, p: 28, c: 1, f: 29, allerg: ["lactose"], regime: "oeuf_lait", cout: 2, unite: "g", rayon: "cr" },
  lait: { nom: "Lait demi-écrémé", kcal: 46, p: 3.2, c: 4.8, f: 1.5, allerg: ["lactose"], regime: "oeuf_lait", cout: 1, unite: "ml", rayon: "cr" },
  kefir: { nom: "Kéfir nature", kcal: 55, p: 3.3, c: 4.5, f: 2.5, allerg: ["lactose"], regime: "oeuf_lait", cout: 2, unite: "ml", rayon: "cr" },
  creme_legere: { nom: "Crème légère 15 %", kcal: 160, p: 2.5, c: 4, f: 15, allerg: ["lactose"], regime: "oeuf_lait", cout: 1, unite: "ml", rayon: "cr" },
  beurre: { nom: "Beurre", kcal: 750, p: 0.7, c: 0.6, f: 82, allerg: ["lactose"], regime: "oeuf_lait", cout: 2, unite: "g", rayon: "cr" },
  tofu_soyeux: { nom: "Tofu soyeux", kcal: 60, p: 6, c: 2, f: 3, allerg: ["soy"], regime: "vegetal", cout: 2, unite: "g", rayon: "cr" },
  yaourt_soja: { nom: "Yaourt au soja nature", kcal: 55, p: 4, c: 3, f: 2.5, allerg: ["soy"], regime: "vegetal", cout: 1, unite: "g", rayon: "cr" },
  yaourt_coco: { nom: "Yaourt au lait de coco", kcal: 130, p: 1, c: 6, f: 11, regime: "vegetal", cout: 3, unite: "g", rayon: "cr" },
  boisson_soja: { nom: "Boisson au soja nature", kcal: 40, p: 3.3, c: 1.5, f: 1.8, allerg: ["soy"], regime: "vegetal", cout: 1, unite: "ml", rayon: "cr" },
  lait_amande: { nom: "Boisson à l'amande", kcal: 24, p: 0.5, c: 0.5, f: 2, allerg: ["nuts"], regime: "vegetal", cout: 2, unite: "ml", rayon: "cr" },
  lait_avoine: { nom: "Boisson à l'avoine", kcal: 46, p: 0.8, c: 7, f: 1.5, allerg: ["gluten"], regime: "vegetal", cout: 2, unite: "ml", rayon: "cr" },
  falafel: { nom: "Falafels", kcal: 330, p: 13, c: 32, f: 17, regime: "vegetal", cout: 2, unite: "g", rayon: "cr" },
  haricots_blancs: { nom: "Haricots blancs cuits", kcal: 120, p: 8, c: 20, f: 0.6, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  pois_casses: { nom: "Pois cassés cuits", kcal: 118, p: 8, c: 21, f: 0.4, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  feves: { nom: "Fèves cuites", kcal: 110, p: 8, c: 18, f: 0.5, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  proteine_pois: { nom: "Protéine de pois", kcal: 375, p: 80, c: 5, f: 5, regime: "vegetal", cout: 3, unite: "g", rayon: "es" },
  // ────────────────────────────────────────────────────────────── glucides
  riz: { nom: "Riz basmati cuit", kcal: 130, p: 2.7, c: 28, f: 0.3, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  riz_complet: { nom: "Riz complet cuit", kcal: 123, p: 2.6, c: 26, f: 1, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  pates: { nom: "Pâtes cuites", kcal: 158, p: 5.8, c: 31, f: 0.9, allerg: ["gluten"], regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  pates_completes: { nom: "Pâtes complètes cuites", kcal: 149, p: 6, c: 30, f: 1.3, allerg: ["gluten"], regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  quinoa: { nom: "Quinoa cuit", kcal: 120, p: 4.4, c: 21, f: 1.9, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  sarrasin: { nom: "Sarrasin cuit", kcal: 92, p: 3.4, c: 20, f: 0.6, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  semoule: { nom: "Semoule cuite", kcal: 112, p: 3.8, c: 23, f: 0.2, allerg: ["gluten"], regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  boulgour: { nom: "Boulgour cuit", kcal: 110, p: 3.5, c: 23, f: 0.3, allerg: ["gluten"], regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  polenta: { nom: "Polenta cuite", kcal: 85, p: 2, c: 18, f: 0.3, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  pomme_de_terre: { nom: "Pommes de terre", kcal: 87, p: 2, c: 20, f: 0.1, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  patate_douce: { nom: "Patate douce", kcal: 90, p: 2, c: 21, f: 0.1, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  pain_complet: { nom: "Pain complet", kcal: 247, p: 9, c: 41, f: 3.4, allerg: ["gluten"], regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  tortilla: { nom: "Galette de blé", kcal: 300, p: 8, c: 50, f: 7, allerg: ["gluten"], regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  avoine: { nom: "Flocons d'avoine", kcal: 375, p: 13, c: 60, f: 7, allerg: ["gluten"], regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  galette_riz: { nom: "Galettes de riz", kcal: 380, p: 8, c: 81, f: 3, regime: "vegetal", cout: 1, piece: 9, pieceLabel: ["galette de riz", "galettes de riz"], rayon: "es" },
  farine_riz: { nom: "Farine de riz", kcal: 366, p: 6, c: 80, f: 1.4, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },

  millet: { nom: "Millet cuit", kcal: 119, p: 3.5, c: 23, f: 1, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  epeautre: { nom: "Épeautre cuit", kcal: 127, p: 5, c: 25, f: 0.9, allerg: ["gluten"], regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  son_avoine: { nom: "Son d'avoine", kcal: 350, p: 17, c: 50, f: 7, allerg: ["gluten"], regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  muesli: { nom: "Muesli sans sucres ajoutés", kcal: 370, p: 10, c: 60, f: 8, allerg: ["gluten"], regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  pain_sans_gluten: { nom: "Pain sans gluten", kcal: 250, p: 5, c: 45, f: 4, regime: "vegetal", cout: 3, unite: "g", rayon: "es" },
  pain_pita: { nom: "Pain pita", kcal: 275, p: 9, c: 55, f: 1.5, allerg: ["gluten"], regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  tortilla_mais: { nom: "Galette de maïs", kcal: 290, p: 7, c: 55, f: 4, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  nouilles_riz: { nom: "Nouilles de riz cuites", kcal: 110, p: 2, c: 25, f: 0.2, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  dattes: { nom: "Dattes", kcal: 282, p: 2.5, c: 68, f: 0.4, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  raisins_secs: { nom: "Raisins secs", kcal: 300, p: 3, c: 75, f: 0.5, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  abricots_secs: { nom: "Abricots secs", kcal: 240, p: 3.4, c: 55, f: 0.5, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  // ───────────────────────────────────────────────────────── fruits, légumes
  banane: { nom: "Banane", kcal: 89, p: 1.1, c: 23, f: 0.3, regime: "vegetal", cout: 1, piece: 120, pieceLabel: ["banane", "bananes"], rayon: "fl" },
  pomme: { nom: "Pomme", kcal: 52, p: 0.3, c: 14, f: 0.2, regime: "vegetal", cout: 1, piece: 150, pieceLabel: ["pomme", "pommes"], rayon: "fl" },
  orange: { nom: "Orange", kcal: 47, p: 0.9, c: 12, f: 0.1, regime: "vegetal", cout: 1, piece: 180, pieceLabel: ["orange", "oranges"], rayon: "fl" },
  myrtilles: { nom: "Myrtilles", kcal: 57, p: 0.7, c: 14, f: 0.3, regime: "vegetal", cout: 3, unite: "g", rayon: "fl" },
  fraises: { nom: "Fraises", kcal: 32, p: 0.7, c: 7.7, f: 0.3, regime: "vegetal", cout: 2, unite: "g", rayon: "fl" },
  compote: { nom: "Compote sans sucres ajoutés", kcal: 45, p: 0.2, c: 11, f: 0.1, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  brocoli: { nom: "Brocoli", kcal: 34, p: 2.8, c: 7, f: 0.4, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  courgette: { nom: "Courgettes", kcal: 17, p: 1.2, c: 3.1, f: 0.3, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  epinards: { nom: "Épinards", kcal: 23, p: 2.9, c: 3.6, f: 0.4, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  haricots_verts: { nom: "Haricots verts", kcal: 31, p: 1.8, c: 7, f: 0.1, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  poivron: { nom: "Poivrons", kcal: 31, p: 1, c: 6, f: 0.3, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  tomate: { nom: "Tomates", kcal: 18, p: 0.9, c: 3.9, f: 0.2, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  carotte: { nom: "Carottes", kcal: 41, p: 0.9, c: 10, f: 0.2, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  chou_fleur: { nom: "Chou-fleur", kcal: 25, p: 1.9, c: 5, f: 0.3, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  salade: { nom: "Salade verte", kcal: 25, p: 2.6, c: 3.7, f: 0.7, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  concombre: { nom: "Concombre", kcal: 15, p: 0.7, c: 3.6, f: 0.1, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  oignon: { nom: "Oignon", kcal: 40, p: 1.1, c: 9, f: 0.1, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  champignons: { nom: "Champignons de Paris", kcal: 22, p: 3.1, c: 3.3, f: 0.3, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  petit_pois: { nom: "Petits pois", kcal: 81, p: 5.4, c: 14, f: 0.4, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  mais: { nom: "Maïs doux", kcal: 86, p: 3.3, c: 19, f: 1.2, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  avocat: { nom: "Avocat", kcal: 160, p: 2, c: 9, f: 15, regime: "vegetal", cout: 3, unite: "g", rayon: "fl" },
  citron: { nom: "Citron", kcal: 29, p: 1, c: 9, f: 0.3, regime: "vegetal", cout: 1, piece: 90, pieceLabel: ["citron", "citrons"], rayon: "fl" },

  framboises: { nom: "Framboises", kcal: 52, p: 1.2, c: 12, f: 0.7, regime: "vegetal", cout: 3, unite: "g", rayon: "fl" },
  mangue: { nom: "Mangue", kcal: 60, p: 0.8, c: 15, f: 0.4, regime: "vegetal", cout: 2, unite: "g", rayon: "fl" },
  ananas: { nom: "Ananas", kcal: 50, p: 0.5, c: 13, f: 0.1, regime: "vegetal", cout: 2, unite: "g", rayon: "fl" },
  kiwi: { nom: "Kiwi", kcal: 61, p: 1.1, c: 15, f: 0.5, regime: "vegetal", cout: 1, piece: 90, pieceLabel: ["kiwi", "kiwis"], rayon: "fl" },
  poire: { nom: "Poire", kcal: 57, p: 0.4, c: 15, f: 0.1, regime: "vegetal", cout: 1, piece: 170, pieceLabel: ["poire", "poires"], rayon: "fl" },
  raisin: { nom: "Raisin", kcal: 69, p: 0.7, c: 18, f: 0.2, regime: "vegetal", cout: 2, unite: "g", rayon: "fl" },
  betterave: { nom: "Betterave cuite", kcal: 43, p: 1.6, c: 10, f: 0.2, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  aubergine: { nom: "Aubergine", kcal: 25, p: 1, c: 6, f: 0.2, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  poireau: { nom: "Poireau", kcal: 29, p: 1.5, c: 6, f: 0.3, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  celeri_rave: { nom: "Céleri-rave", kcal: 42, p: 1.5, c: 9, f: 0.3, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  chou_rouge: { nom: "Chou rouge", kcal: 31, p: 1.4, c: 7, f: 0.2, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  kale: { nom: "Chou kale", kcal: 49, p: 4.3, c: 9, f: 0.9, regime: "vegetal", cout: 2, unite: "g", rayon: "fl" },
  endive: { nom: "Endives", kcal: 17, p: 1, c: 3.4, f: 0.1, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  fenouil: { nom: "Fenouil", kcal: 31, p: 1.2, c: 7, f: 0.2, regime: "vegetal", cout: 2, unite: "g", rayon: "fl" },
  asperges: { nom: "Asperges vertes", kcal: 20, p: 2.2, c: 3.9, f: 0.1, regime: "vegetal", cout: 3, unite: "g", rayon: "fl" },
  butternut: { nom: "Courge butternut", kcal: 45, p: 1, c: 12, f: 0.1, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  panais: { nom: "Panais", kcal: 75, p: 1.2, c: 18, f: 0.3, regime: "vegetal", cout: 2, unite: "g", rayon: "fl" },
  roquette: { nom: "Roquette", kcal: 25, p: 2.6, c: 3.7, f: 0.7, regime: "vegetal", cout: 2, unite: "g", rayon: "fl" },
  mache: { nom: "Mâche", kcal: 21, p: 2, c: 3.6, f: 0.4, regime: "vegetal", cout: 2, unite: "g", rayon: "fl" },
  tomates_cerises: { nom: "Tomates cerises", kcal: 18, p: 0.9, c: 3.9, f: 0.2, regime: "vegetal", cout: 2, unite: "g", rayon: "fl" },
  oignon_rouge: { nom: "Oignon rouge", kcal: 40, p: 1.1, c: 9, f: 0.1, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },
  radis: { nom: "Radis", kcal: 16, p: 0.7, c: 3.4, f: 0.1, regime: "vegetal", cout: 1, unite: "g", rayon: "fl" },

  // ──────────────────────────────────────────────────────── lipides, extras
  huile_olive: { nom: "Huile d'olive", kcal: 884, p: 0, c: 0, f: 100, regime: "vegetal", cout: 2, unite: "g", rayon: "lc" },
  beurre_cacahuete: { nom: "Beurre de cacahuète", kcal: 588, p: 25, c: 20, f: 50, allerg: ["nuts"], regime: "vegetal", cout: 3, unite: "g", rayon: "lc" },
  amandes: { nom: "Amandes", kcal: 579, p: 21, c: 22, f: 50, allerg: ["nuts"], regime: "vegetal", cout: 3, unite: "g", rayon: "es" },
  noix: { nom: "Cerneaux de noix", kcal: 654, p: 15, c: 14, f: 65, allerg: ["nuts"], regime: "vegetal", cout: 3, unite: "g", rayon: "es" },
  graines_courge: { nom: "Graines de courge", kcal: 559, p: 30, c: 11, f: 49, regime: "vegetal", cout: 3, unite: "g", rayon: "es" },
  graines_chia: { nom: "Graines de chia", kcal: 486, p: 17, c: 42, f: 31, regime: "vegetal", cout: 3, unite: "g", rayon: "es" },
  lait_coco: { nom: "Lait de coco", kcal: 197, p: 2, c: 3, f: 20, regime: "vegetal", cout: 2, unite: "ml", rayon: "lc" },
  olives: { nom: "Olives dénoyautées", kcal: 145, p: 1, c: 6, f: 15, regime: "vegetal", cout: 2, unite: "g", rayon: "lc" },
  houmous: { nom: "Houmous", kcal: 237, p: 7.5, c: 14, f: 18, regime: "vegetal", cout: 2, unite: "g", rayon: "cr" },
  miel: { nom: "Miel", kcal: 304, p: 0.3, c: 82, f: 0, regime: "vegetal", cout: 1, unite: "g", rayon: "lc" },
  sirop_erable: { nom: "Sirop d'érable", kcal: 260, p: 0, c: 67, f: 0, regime: "vegetal", cout: 3, unite: "g", rayon: "lc" },
  chocolat_noir: { nom: "Chocolat noir 70 %", kcal: 546, p: 8, c: 46, f: 31, regime: "vegetal", cout: 3, unite: "g", rayon: "es" },
  sauce_soja: { nom: "Sauce soja", kcal: 53, p: 8, c: 5, f: 0, allerg: ["soy"], regime: "vegetal", cout: 1, unite: "ml", rayon: "lc" },
  cacao: { nom: "Cacao non sucré", kcal: 228, p: 20, c: 58, f: 14, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  huile_colza: { nom: "Huile de colza", kcal: 884, p: 0, c: 0, f: 100, regime: "vegetal", cout: 2, unite: "g", rayon: "lc" },
  noisettes: { nom: "Noisettes", kcal: 630, p: 15, c: 17, f: 61, allerg: ["nuts"], regime: "vegetal", cout: 3, unite: "g", rayon: "es" },
  noix_cajou: { nom: "Noix de cajou", kcal: 553, p: 18, c: 30, f: 44, allerg: ["nuts"], regime: "vegetal", cout: 3, unite: "g", rayon: "es" },
  cacahuetes: { nom: "Cacahuètes grillées", kcal: 567, p: 26, c: 16, f: 49, allerg: ["nuts"], regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  graines_tournesol: { nom: "Graines de tournesol", kcal: 584, p: 21, c: 20, f: 51, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  graines_lin: { nom: "Graines de lin moulues", kcal: 534, p: 18, c: 29, f: 42, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  coco_rapee: { nom: "Noix de coco râpée", kcal: 604, p: 6.9, c: 24, f: 65, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  tahini: { nom: "Purée de sésame", kcal: 595, p: 17, c: 21, f: 54, regime: "vegetal", cout: 3, unite: "g", rayon: "lc" },
  tomates_concassees: { nom: "Tomates concassées", kcal: 32, p: 1.3, c: 5, f: 0.3, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  passata: { nom: "Coulis de tomate", kcal: 35, p: 1.5, c: 6, f: 0.2, regime: "vegetal", cout: 1, unite: "g", rayon: "es" },
  creme_soja: { nom: "Crème de soja", kcal: 180, p: 3, c: 3, f: 17, allerg: ["soy"], regime: "vegetal", cout: 2, unite: "ml", rayon: "lc" },
  moutarde: { nom: "Moutarde", kcal: 66, p: 4, c: 5, f: 3, regime: "vegetal", cout: 1, unite: "g", rayon: "lc" },
  vinaigre: { nom: "Vinaigre balsamique", kcal: 88, p: 0.5, c: 17, f: 0, regime: "vegetal", cout: 1, unite: "ml", rayon: "lc" },
  pesto: { nom: "Pesto", kcal: 450, p: 5, c: 5, f: 45, allerg: ["nuts", "lactose"], regime: "oeuf_lait", cout: 3, unite: "g", rayon: "lc" },
  levure_maltee: { nom: "Levure maltée", kcal: 380, p: 45, c: 20, f: 5, regime: "vegetal", cout: 2, unite: "g", rayon: "es" },
  harissa: { nom: "Harissa", kcal: 100, p: 3, c: 10, f: 5, regime: "vegetal", cout: 1, unite: "g", rayon: "lc" },
};

/** Moment du repas. Décide de la part des macros du jour et du ton du plat. */
export type Repas = "petit-dejeuner" | "dejeuner" | "diner" | "collation";

/**
 * Rôle d'ajustement. L'ingrédient marqué voit sa quantité CALCULÉE pour
 * atteindre la cible du repas ; les autres gardent la quantité écrite ici.
 * Une recette sans ancre de lipides laisse simplement le gras là où il est.
 */
export type Role = "proteine" | "glucide" | "lipide";

export interface Ingredient {
  /** Clé dans `FOODS`. */
  food: string;
  /** Quantité de référence, en grammes (ou en pièces converties en grammes). */
  qty: number;
  role?: Role;
  /** Bornes de l'ajustement, en grammes. Par défaut 40 % à 220 % de `qty`. */
  min?: number;
  max?: number;
}

export interface RecipeTemplate {
  id: string;
  nom: string;
  repas: Repas;
  /** 0 assemblage sans cuisson, 1 simple, 2 élaboré. */
  effort: 0 | 1 | 2;
  /** Temps total, en minutes. */
  minutes: number;
  ingredients: Ingredient[];
}

export const RECIPES: readonly RecipeTemplate[] = [
  // ═══════════════════════════════════════════════════ petit-déjeuner (10)
  {
    id: "pdj-avoine-skyr",
    nom: "Porridge d'avoine au skyr et fruits rouges",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 10,
    ingredients: [
      { food: "avoine", qty: 70, role: "glucide" },
      { food: "skyr", qty: 200, role: "proteine" },
      { food: "myrtilles", qty: 100 },
      { food: "beurre_cacahuete", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "pdj-omelette-pain",
    nom: "Omelette aux champignons et pain complet",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 12,
    ingredients: [
      { food: "oeuf", qty: 165, role: "proteine", min: 110, max: 275 },
      { food: "champignons", qty: 100 },
      { food: "pain_complet", qty: 80, role: "glucide" },
      { food: "huile_olive", qty: 8, role: "lipide" },
    ],
  },
  {
    id: "pdj-pancakes",
    nom: "Pancakes protéinés à la banane",
    repas: "petit-dejeuner",
    effort: 2,
    minutes: 20,
    ingredients: [
      { food: "farine_riz", qty: 70, role: "glucide" },
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 220 },
      { food: "fromage_blanc", qty: 150 },
      { food: "banane", qty: 120 },
      { food: "sirop_erable", qty: 15 },
    ],
  },
  {
    id: "pdj-bowl-coco",
    nom: "Bowl de riz au lait de coco et fruits",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 15,
    ingredients: [
      { food: "riz", qty: 200, role: "glucide" },
      { food: "lait_coco", qty: 80, role: "lipide" },
      { food: "banane", qty: 120 },
      { food: "graines_courge", qty: 20 },
      { food: "whey", qty: 25, role: "proteine", min: 10, max: 50 },
    ],
  },
  {
    id: "pdj-toast-avocat",
    nom: "Toast avocat et œufs pochés",
    repas: "petit-dejeuner",
    effort: 2,
    minutes: 15,
    ingredients: [
      { food: "pain_complet", qty: 80, role: "glucide" },
      { food: "avocat", qty: 60, role: "lipide" },
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 220 },
      { food: "tomate", qty: 80 },
      { food: "citron", qty: 20 },
    ],
  },
  {
    id: "pdj-skyr-express",
    nom: "Bol de skyr, avoine et miel",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 5,
    ingredients: [
      { food: "skyr", qty: 250, role: "proteine" },
      { food: "avoine", qty: 50, role: "glucide" },
      { food: "miel", qty: 15 },
      { food: "amandes", qty: 20, role: "lipide" },
    ],
  },
  {
    id: "pdj-tofu-brouille",
    nom: "Tofu brouillé aux poivrons",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 12,
    ingredients: [
      { food: "tofu", qty: 200, role: "proteine" },
      { food: "poivron", qty: 120 },
      { food: "pain_complet", qty: 70, role: "glucide" },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "pdj-porridge-chia",
    nom: "Pudding de chia au cacao",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 5,
    ingredients: [
      { food: "graines_chia", qty: 30, role: "lipide" },
      { food: "fromage_blanc", qty: 250, role: "proteine" },
      { food: "cacao", qty: 10 },
      { food: "avoine", qty: 45, role: "glucide" },
      { food: "banane", qty: 120 },
      { food: "miel", qty: 10 },
    ],
  },
  {
    id: "pdj-cottage-fruits",
    nom: "Cottage cheese, fruits frais et galettes",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 5,
    ingredients: [
      { food: "cottage", qty: 220, role: "proteine" },
      { food: "galette_riz", qty: 36, role: "glucide", min: 18, max: 72 },
      { food: "fraises", qty: 120 },
      { food: "noix", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "pdj-wrap-jambon",
    nom: "Wrap œuf et jambon",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 10,
    ingredients: [
      { food: "tortilla", qty: 60, role: "glucide" },
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 165 },
      { food: "jambon", qty: 60 },
      { food: "salade", qty: 40 },
      { food: "huile_olive", qty: 6, role: "lipide" },
    ],
  },

  // ═════════════════════════════════════════════════════════ déjeuner (12)
  {
    id: "dej-poulet-riz",
    nom: "Poulet grillé, riz basmati et courgettes",
    repas: "dejeuner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "poulet", qty: 180, role: "proteine" },
      { food: "riz", qty: 220, role: "glucide" },
      { food: "courgette", qty: 200 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-boeuf-patate",
    nom: "Bœuf haché, patate douce rôtie et haricots verts",
    repas: "dejeuner",
    effort: 1,
    minutes: 35,
    ingredients: [
      { food: "boeuf", qty: 160, role: "proteine" },
      { food: "patate_douce", qty: 280, role: "glucide" },
      { food: "haricots_verts", qty: 200 },
      { food: "huile_olive", qty: 8, role: "lipide" },
    ],
  },
  {
    id: "dej-cabillaud-quinoa",
    nom: "Cabillaud au citron, quinoa et poivrons",
    repas: "dejeuner",
    effort: 2,
    minutes: 30,
    ingredients: [
      { food: "cabillaud", qty: 200, role: "proteine" },
      { food: "quinoa", qty: 220, role: "glucide" },
      { food: "poivron", qty: 180 },
      { food: "huile_olive", qty: 12, role: "lipide" },
      { food: "citron", qty: 30 },
    ],
  },
  {
    id: "dej-dahl",
    nom: "Dahl de lentilles corail au lait de coco",
    repas: "dejeuner",
    effort: 2,
    minutes: 30,
    ingredients: [
      { food: "lentilles_corail", qty: 110, role: "proteine" },
      { food: "riz_complet", qty: 180, role: "glucide" },
      { food: "lait_coco", qty: 60, role: "lipide" },
      { food: "epinards", qty: 150 },
      { food: "oignon", qty: 80 },
    ],
  },
  {
    id: "dej-tofu-sarrasin",
    nom: "Bowl tofu croustillant, sarrasin et brocoli",
    repas: "dejeuner",
    effort: 2,
    minutes: 30,
    ingredients: [
      { food: "tofu", qty: 200, role: "proteine" },
      { food: "sarrasin", qty: 200, role: "glucide" },
      { food: "brocoli", qty: 180 },
      { food: "sauce_soja", qty: 15 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "dej-dinde-pates",
    nom: "Pâtes complètes, dinde et tomates",
    repas: "dejeuner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "dinde", qty: 170, role: "proteine" },
      { food: "pates_completes", qty: 230, role: "glucide" },
      { food: "tomate", qty: 200 },
      { food: "huile_olive", qty: 12, role: "lipide" },
      { food: "parmesan", qty: 15 },
    ],
  },
  {
    id: "dej-buddha-pois-chiches",
    nom: "Buddha bowl pois chiches et patate douce",
    repas: "dejeuner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "pois_chiches", qty: 200, role: "proteine" },
      { food: "patate_douce", qty: 250, role: "glucide" },
      { food: "salade", qty: 60 },
      { food: "avocat", qty: 60, role: "lipide" },
      { food: "citron", qty: 25 },
    ],
  },
  {
    id: "dej-thon-boulgour",
    nom: "Salade de boulgour au thon",
    repas: "dejeuner",
    effort: 0,
    minutes: 10,
    ingredients: [
      { food: "thon", qty: 150, role: "proteine" },
      { food: "boulgour", qty: 230, role: "glucide" },
      { food: "concombre", qty: 120 },
      { food: "tomate", qty: 120 },
      { food: "huile_olive", qty: 14, role: "lipide" },
      { food: "citron", qty: 25 },
    ],
  },
  {
    id: "dej-poulet-wrap",
    nom: "Wrap poulet crudités",
    repas: "dejeuner",
    effort: 1,
    minutes: 15,
    ingredients: [
      { food: "poulet", qty: 160, role: "proteine" },
      { food: "tortilla", qty: 120, role: "glucide" },
      { food: "salade", qty: 50 },
      { food: "tomate", qty: 80 },
      { food: "houmous", qty: 40, role: "lipide" },
    ],
  },
  {
    id: "dej-crevettes-riz",
    nom: "Riz sauté aux crevettes et petits pois",
    repas: "dejeuner",
    effort: 2,
    minutes: 20,
    ingredients: [
      { food: "crevettes", qty: 180, role: "proteine" },
      { food: "riz", qty: 220, role: "glucide" },
      { food: "petit_pois", qty: 120 },
      { food: "oeuf", qty: 55 },
      { food: "sauce_soja", qty: 15 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "dej-seitan-poelee",
    nom: "Poêlée de seitan et légumes racines",
    repas: "dejeuner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "seitan", qty: 160, role: "proteine" },
      { food: "pomme_de_terre", qty: 250, role: "glucide" },
      { food: "carotte", qty: 150 },
      { food: "oignon", qty: 70 },
      { food: "huile_olive", qty: 14, role: "lipide" },
    ],
  },
  {
    id: "dej-omelette-pois-chiches",
    nom: "Grande omelette et salade de pois chiches",
    repas: "dejeuner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "oeuf", qty: 165, role: "proteine", min: 110, max: 275 },
      { food: "pois_chiches", qty: 200, role: "glucide" },
      { food: "salade", qty: 80 },
      { food: "feta", qty: 40 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },

  // ═══════════════════════════════════════════════════════════ dîner (12)
  {
    id: "din-saumon-patate",
    nom: "Saumon rôti et patate douce, épinards à l'ail",
    repas: "diner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "saumon", qty: 150, role: "proteine" },
      { food: "patate_douce", qty: 250, role: "glucide" },
      { food: "epinards", qty: 150 },
      { food: "huile_olive", qty: 8, role: "lipide" },
    ],
  },
  {
    id: "din-dinde-puree",
    nom: "Dinde et purée de céleri et pomme de terre",
    repas: "diner",
    effort: 2,
    minutes: 35,
    ingredients: [
      { food: "dinde", qty: 170, role: "proteine" },
      { food: "pomme_de_terre", qty: 200, role: "glucide" },
      { food: "carotte", qty: 150 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "din-curry-legumes",
    nom: "Curry de pois chiches et chou-fleur",
    repas: "diner",
    effort: 2,
    minutes: 30,
    ingredients: [
      { food: "pois_chiches", qty: 220, role: "proteine" },
      { food: "riz", qty: 180, role: "glucide" },
      { food: "chou_fleur", qty: 200 },
      { food: "lait_coco", qty: 60, role: "lipide" },
      { food: "oignon", qty: 80 },
    ],
  },
  {
    id: "din-cabillaud-polenta",
    nom: "Cabillaud, polenta crémeuse et brocoli",
    repas: "diner",
    effort: 2,
    minutes: 25,
    ingredients: [
      { food: "cabillaud", qty: 200, role: "proteine" },
      { food: "polenta", qty: 250, role: "glucide" },
      { food: "brocoli", qty: 180 },
      { food: "parmesan", qty: 20 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-poulet-ratatouille",
    nom: "Poulet et ratatouille au four",
    repas: "diner",
    effort: 2,
    minutes: 45,
    ingredients: [
      { food: "poulet", qty: 180, role: "proteine" },
      { food: "courgette", qty: 200 },
      { food: "poivron", qty: 150 },
      { food: "tomate", qty: 200 },
      { food: "pomme_de_terre", qty: 200, role: "glucide" },
      { food: "huile_olive", qty: 14, role: "lipide" },
    ],
  },
  {
    id: "din-tortilla-pdt",
    nom: "Tortilla de pommes de terre",
    repas: "diner",
    effort: 2,
    minutes: 35,
    ingredients: [
      { food: "oeuf", qty: 220, role: "proteine", min: 110, max: 330 },
      { food: "pomme_de_terre", qty: 300, role: "glucide" },
      { food: "oignon", qty: 100 },
      { food: "huile_olive", qty: 16, role: "lipide" },
      { food: "salade", qty: 60 },
    ],
  },
  {
    id: "din-sardines-salade",
    nom: "Sardines, salade de pommes de terre et haricots",
    repas: "diner",
    effort: 0,
    minutes: 15,
    ingredients: [
      { food: "sardines", qty: 120, role: "proteine" },
      { food: "pomme_de_terre", qty: 280, role: "glucide" },
      { food: "haricots_verts", qty: 150 },
      { food: "oignon", qty: 40 },
      { food: "huile_olive", qty: 10, role: "lipide" },
      { food: "citron", qty: 25 },
    ],
  },
  {
    id: "din-tempeh-legumes",
    nom: "Tempeh laqué et légumes vapeur",
    repas: "diner",
    effort: 2,
    minutes: 25,
    ingredients: [
      { food: "tempeh", qty: 170, role: "proteine" },
      { food: "riz_complet", qty: 200, role: "glucide" },
      { food: "brocoli", qty: 150 },
      { food: "carotte", qty: 100 },
      { food: "sauce_soja", qty: 20 },
      { food: "huile_olive", qty: 12, role: "lipide" },
      { food: "miel", qty: 10 },
    ],
  },
  {
    id: "din-soupe-lentilles",
    nom: "Soupe épaisse de lentilles et légumes",
    repas: "diner",
    effort: 1,
    minutes: 35,
    ingredients: [
      { food: "lentilles", qty: 250, role: "proteine" },
      { food: "pomme_de_terre", qty: 200, role: "glucide" },
      { food: "carotte", qty: 150 },
      { food: "oignon", qty: 80 },
      { food: "huile_olive", qty: 14, role: "lipide" },
      { food: "pain_complet", qty: 50 },
    ],
  },
  {
    id: "din-poulet-salade-cesar",
    nom: "Salade complète poulet, œuf et croûtons",
    repas: "diner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "poulet", qty: 160, role: "proteine" },
      { food: "pain_complet", qty: 80, role: "glucide" },
      { food: "salade", qty: 100 },
      { food: "oeuf", qty: 55 },
      { food: "yaourt_grec", qty: 60 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "din-chili-vegetarien",
    nom: "Chili de haricots rouges",
    repas: "diner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "haricots_rouges", qty: 250, role: "proteine" },
      { food: "riz", qty: 180, role: "glucide" },
      { food: "tomate", qty: 200 },
      { food: "poivron", qty: 120 },
      { food: "mais", qty: 80 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-gratin-courgettes",
    nom: "Gratin de courgettes au thon",
    repas: "diner",
    effort: 2,
    minutes: 40,
    ingredients: [
      { food: "thon", qty: 150, role: "proteine" },
      { food: "courgette", qty: 300 },
      { food: "pomme_de_terre", qty: 220, role: "glucide" },
      { food: "mozzarella", qty: 60, role: "lipide" },
      { food: "oeuf", qty: 55 },
    ],
  },

  // ══════════════════════════════════════════════════════════ collation (6)
  {
    id: "col-skyr-miel",
    nom: "Skyr, miel et amandes",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "skyr", qty: 200, role: "proteine" },
      { food: "miel", qty: 15, role: "glucide" },
      { food: "amandes", qty: 20, role: "lipide" },
    ],
  },
  {
    id: "col-banane-cacahuete",
    nom: "Galettes de riz, banane et beurre de cacahuète",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "galette_riz", qty: 27, role: "glucide", min: 9, max: 63 },
      { food: "banane", qty: 120 },
      { food: "beurre_cacahuete", qty: 20, role: "lipide" },
      { food: "skyr", qty: 150, role: "proteine" },
    ],
  },
  {
    id: "col-toast-houmous",
    nom: "Toast houmous et tomates cerises",
    repas: "collation",
    effort: 0,
    minutes: 5,
    ingredients: [
      { food: "pain_complet", qty: 60, role: "glucide" },
      { food: "houmous", qty: 60, role: "lipide" },
      { food: "tomate", qty: 100 },
      { food: "feta", qty: 30, role: "proteine" },
    ],
  },
  {
    id: "col-shake-avoine",
    nom: "Shake avoine, banane et cacao",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "whey", qty: 30, role: "proteine", min: 15, max: 50 },
      { food: "avoine", qty: 40, role: "glucide" },
      { food: "banane", qty: 120 },
      { food: "cacao", qty: 8 },
      { food: "beurre_cacahuete", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "col-fruits-noix",
    nom: "Pomme, noix et compote",
    repas: "collation",
    effort: 0,
    minutes: 2,
    ingredients: [
      { food: "pomme", qty: 150, role: "glucide" },
      { food: "noix", qty: 20, role: "lipide" },
      { food: "compote", qty: 100 },
      { food: "fromage_blanc", qty: 150, role: "proteine" },
    ],
  },
  {
    id: "col-oeufs-durs",
    nom: "Œufs durs et crudités",
    repas: "collation",
    effort: 1,
    minutes: 12,
    ingredients: [
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 220 },
      { food: "pain_complet", qty: 60, role: "glucide" },
      { food: "carotte", qty: 120 },
      { food: "concombre", qty: 100 },
      { food: "houmous", qty: 40, role: "lipide" },
    ],
  },
  // ══════════════════════════════════ petit-déjeuner, élargissement (22)
  {
    id: "pdj-overnight-soja",
    nom: "Overnight oats au yaourt de soja et banane",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 5,
    ingredients: [
      { food: "avoine", qty: 70, role: "glucide" },
      { food: "yaourt_soja", qty: 180 },
      { food: "proteine_pois", qty: 20, role: "proteine" },
      { food: "banane", qty: 120 },
      { food: "graines_lin", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "pdj-porridge-millet",
    nom: "Porridge de millet, poire et graines",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 12,
    ingredients: [
      { food: "millet", qty: 180, role: "glucide" },
      { food: "boisson_soja", qty: 200 },
      { food: "proteine_pois", qty: 25, role: "proteine" },
      { food: "poire", qty: 170 },
      { food: "graines_tournesol", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "pdj-skyr-kiwi-graines",
    nom: "Skyr, kiwi et graines de tournesol",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "skyr", qty: 220, role: "proteine" },
      { food: "kiwi", qty: 90 },
      { food: "miel", qty: 15, role: "glucide" },
      { food: "graines_tournesol", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "pdj-oeufs-pdt",
    nom: "Œufs brouillés et pommes de terre sautées",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 15,
    ingredients: [
      { food: "oeuf", qty: 165, role: "proteine", min: 110, max: 275 },
      { food: "pomme_de_terre", qty: 250, role: "glucide" },
      { food: "poivron", qty: 100 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "pdj-pain-perdu",
    nom: "Pain perdu protéiné à la cannelle",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 12,
    ingredients: [
      { food: "pain_complet", qty: 90, role: "glucide" },
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 220 },
      { food: "lait", qty: 100 },
      { food: "miel", qty: 12 },
    ],
  },
  {
    id: "pdj-cottage-ananas",
    nom: "Cottage cheese, ananas et muesli",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "cottage", qty: 200, role: "proteine" },
      { food: "ananas", qty: 120 },
      { food: "muesli", qty: 60, role: "glucide" },
      { food: "graines_lin", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "pdj-tartine-ricotta-raisin",
    nom: "Tartines ricotta, raisin et miel",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 5,
    ingredients: [
      { food: "pain_complet", qty: 90, role: "glucide" },
      { food: "ricotta", qty: 150, role: "proteine" },
      { food: "raisin", qty: 100 },
      { food: "miel", qty: 12 },
    ],
  },
  {
    id: "pdj-shake-vegetal",
    nom: "Shake végétal banane et cacao",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "boisson_soja", qty: 300, min: 200, max: 400 },
      { food: "proteine_pois", qty: 30, role: "proteine" },
      { food: "banane", qty: 120, role: "glucide" },
      { food: "cacao", qty: 8 },
    ],
  },
  {
    id: "pdj-omelette-feta",
    nom: "Omelette épinards et feta",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 12,
    ingredients: [
      { food: "oeuf", qty: 165, role: "proteine", min: 110, max: 275 },
      { food: "epinards", qty: 120 },
      { food: "feta", qty: 40 },
      { food: "pain_complet", qty: 70, role: "glucide" },
      { food: "huile_olive", qty: 8, role: "lipide" },
    ],
  },
  {
    id: "pdj-galette-mais-jambon",
    nom: "Galette de maïs, jambon et œuf",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 10,
    ingredients: [
      { food: "tortilla_mais", qty: 70, role: "glucide" },
      { food: "jambon", qty: 60 },
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 220 },
      { food: "emmental", qty: 25, role: "lipide" },
    ],
  },
  {
    id: "pdj-son-avoine-whey",
    nom: "Porridge express au son d'avoine",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 6,
    ingredients: [
      { food: "son_avoine", qty: 60, role: "glucide" },
      { food: "lait", qty: 200 },
      { food: "whey", qty: 25, role: "proteine" },
      { food: "myrtilles", qty: 80 },
    ],
  },
  {
    id: "pdj-yaourt-coco-mangue",
    nom: "Yaourt de coco, mangue et noix de coco",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "yaourt_coco", qty: 150, role: "lipide", min: 80, max: 220 },
      { food: "mangue", qty: 150, role: "glucide" },
      { food: "coco_rapee", qty: 15 },
      { food: "proteine_pois", qty: 25, role: "proteine" },
    ],
  },
  {
    id: "pdj-tofu-epinards",
    nom: "Tofu brouillé, épinards et pain grillé",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 12,
    ingredients: [
      { food: "tofu", qty: 180, role: "proteine" },
      { food: "epinards", qty: 120 },
      { food: "pain_complet", qty: 80, role: "glucide" },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "pdj-muesli-kefir",
    nom: "Muesli, kéfir et poire",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "muesli", qty: 70, role: "glucide" },
      { food: "kefir", qty: 150 },
      { food: "skyr", qty: 150, role: "proteine" },
      { food: "poire", qty: 170 },
      { food: "noisettes", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "pdj-crepes-avoine",
    nom: "Crêpes d'avoine à la banane",
    repas: "petit-dejeuner",
    effort: 2,
    minutes: 20,
    ingredients: [
      { food: "avoine", qty: 80, role: "glucide" },
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 220 },
      { food: "banane", qty: 120 },
      { food: "lait", qty: 120 },
    ],
  },
  {
    id: "pdj-fromage-blanc-abricots",
    nom: "Fromage blanc, abricots secs et graines",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "fromage_blanc", qty: 220, role: "proteine" },
      { food: "abricots_secs", qty: 50, role: "glucide" },
      { food: "graines_tournesol", qty: 15, role: "lipide" },
      { food: "pomme", qty: 150 },
    ],
  },
  {
    id: "pdj-toast-saumon-fume",
    nom: "Toast au saumon fumé et fromage frais",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 6,
    ingredients: [
      { food: "pain_complet", qty: 90, role: "glucide" },
      { food: "saumon_fume", qty: 80 },
      { food: "chevre", qty: 60, role: "proteine" },
      { food: "concombre", qty: 80 },
    ],
  },
  {
    id: "pdj-riz-au-lait",
    nom: "Riz au lait protéiné aux raisins",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 12,
    ingredients: [
      { food: "riz", qty: 200, role: "glucide" },
      { food: "lait", qty: 200 },
      { food: "whey", qty: 25, role: "proteine" },
      { food: "raisins_secs", qty: 25 },
    ],
  },
  {
    id: "pdj-smoothie-bowl-rouge",
    nom: "Smoothie bowl fruits rouges",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 7,
    ingredients: [
      { food: "fraises", qty: 150 },
      { food: "framboises", qty: 80 },
      { food: "skyr", qty: 200, role: "proteine" },
      { food: "avoine", qty: 50, role: "glucide" },
      { food: "graines_chia", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "pdj-wrap-oeuf-avocat",
    nom: "Wrap œuf et avocat",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 10,
    ingredients: [
      { food: "tortilla", qty: 80, role: "glucide" },
      { food: "oeuf", qty: 165, role: "proteine", min: 110, max: 220 },
      { food: "avocat", qty: 70, role: "lipide" },
      { food: "tomate", qty: 80 },
    ],
  },
  {
    id: "pdj-porridge-sarrasin",
    nom: "Porridge de sarrasin à la pomme",
    repas: "petit-dejeuner",
    effort: 1,
    minutes: 12,
    ingredients: [
      { food: "sarrasin", qty: 200, role: "glucide" },
      { food: "proteine_pois", qty: 25, role: "proteine" },
      { food: "pomme", qty: 150 },
      { food: "graines_lin", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "pdj-smoothie-vert",
    nom: "Smoothie vert épinards et banane",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 5,
    ingredients: [
      { food: "epinards", qty: 80 },
      { food: "banane", qty: 150, role: "glucide" },
      { food: "proteine_pois", qty: 30, role: "proteine" },
      { food: "graines_courge", qty: 15, role: "lipide" },
    ],
  },
  // ═══════════════════════════════════════ déjeuner, élargissement (30)
  {
    id: "dej-poulet-quinoa-brocoli",
    nom: "Poulet grillé, quinoa et brocoli",
    repas: "dejeuner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "poulet", qty: 180, role: "proteine" },
      { food: "quinoa", qty: 200, role: "glucide" },
      { food: "brocoli", qty: 180 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-poulet-patate-haricots",
    nom: "Cuisse de poulet, patate douce et haricots verts",
    repas: "dejeuner",
    effort: 1,
    minutes: 35,
    ingredients: [
      { food: "poulet_cuisse", qty: 200, role: "proteine" },
      { food: "patate_douce", qty: 280, role: "glucide" },
      { food: "haricots_verts", qty: 180 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-steak-riz-poivrons",
    nom: "Steak haché, riz et poivrons sautés",
    repas: "dejeuner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "steak_hache", qty: 160, role: "proteine" },
      { food: "riz", qty: 220, role: "glucide" },
      { food: "poivron", qty: 180 },
      { food: "huile_olive", qty: 8, role: "lipide" },
    ],
  },
  {
    id: "dej-colin-pdt-brocoli",
    nom: "Dos de colin, pommes de terre vapeur et brocoli",
    repas: "dejeuner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "colin", qty: 200, role: "proteine" },
      { food: "pomme_de_terre", qty: 280, role: "glucide" },
      { food: "brocoli", qty: 180 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-maquereau-boulgour",
    nom: "Maquereau grillé et boulgour aux herbes",
    repas: "dejeuner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "maquereau", qty: 160, role: "proteine" },
      { food: "boulgour", qty: 200, role: "glucide" },
      { food: "tomate", qty: 150 },
      { food: "citron", qty: 90 },
      { food: "huile_olive", qty: 8, role: "lipide" },
    ],
  },
  {
    id: "dej-salade-thon-pois-chiches",
    nom: "Salade de thon et pois chiches",
    repas: "dejeuner",
    effort: 0,
    minutes: 10,
    ingredients: [
      { food: "thon", qty: 120, role: "proteine" },
      { food: "pois_chiches", qty: 200, role: "glucide" },
      { food: "tomates_cerises", qty: 150 },
      { food: "oignon_rouge", qty: 40 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "dej-salade-poulet-avocat",
    nom: "Salade de poulet, avocat et maïs",
    repas: "dejeuner",
    effort: 0,
    minutes: 12,
    ingredients: [
      { food: "poulet", qty: 170, role: "proteine" },
      { food: "salade", qty: 100 },
      { food: "avocat", qty: 80, role: "lipide" },
      { food: "mais", qty: 150, role: "glucide" },
      { food: "tomate", qty: 120 },
    ],
  },
  {
    id: "dej-curry-lentilles-corail",
    nom: "Curry de lentilles corail au lait de coco",
    repas: "dejeuner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "lentilles_corail", qty: 90, role: "proteine" },
      { food: "riz", qty: 200, role: "glucide" },
      { food: "tomates_concassees", qty: 200 },
      { food: "lait_coco", qty: 60, role: "lipide" },
      { food: "epinards", qty: 120 },
    ],
  },
  {
    id: "dej-chili-quinoa",
    nom: "Chili de haricots rouges au quinoa",
    repas: "dejeuner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "haricots_rouges", qty: 220, role: "proteine" },
      { food: "quinoa", qty: 180, role: "glucide" },
      { food: "passata", qty: 150 },
      { food: "poivron", qty: 120 },
      { food: "mais", qty: 80 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-bowl-tofu-nouilles",
    nom: "Bowl tofu et nouilles de riz sautées",
    repas: "dejeuner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "tofu", qty: 180, role: "proteine" },
      { food: "nouilles_riz", qty: 220, role: "glucide" },
      { food: "chou_rouge", qty: 100 },
      { food: "carotte", qty: 100 },
      { food: "sauce_soja", qty: 15 },
      { food: "huile_colza", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-tempeh-riz-complet",
    nom: "Tempeh laqué, riz complet et brocoli",
    repas: "dejeuner",
    effort: 1,
    minutes: 22,
    ingredients: [
      { food: "tempeh", qty: 170, role: "proteine" },
      { food: "riz_complet", qty: 200, role: "glucide" },
      { food: "brocoli", qty: 180 },
      { food: "sauce_soja", qty: 15 },
      { food: "huile_colza", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-falafel-pita",
    nom: "Pita falafels, houmous et sauce au yaourt",
    repas: "dejeuner",
    effort: 1,
    minutes: 15,
    ingredients: [
      { food: "falafel", qty: 120 },
      { food: "skyr", qty: 150, role: "proteine" },
      { food: "pain_pita", qty: 100, role: "glucide" },
      { food: "houmous", qty: 60, role: "lipide" },
      { food: "tomate", qty: 100 },
      { food: "salade", qty: 60 },
    ],
  },
  {
    id: "dej-buddha-millet-feves",
    nom: "Buddha bowl millet, fèves et betterave",
    repas: "dejeuner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "millet", qty: 200, role: "glucide" },
      { food: "feves", qty: 180, role: "proteine" },
      { food: "betterave", qty: 120 },
      { food: "roquette", qty: 60 },
      { food: "tahini", qty: 20, role: "lipide" },
    ],
  },
  {
    id: "dej-omelette-pdt-salade",
    nom: "Omelette aux pommes de terre et salade verte",
    repas: "dejeuner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "oeuf", qty: 220, role: "proteine", min: 110, max: 330 },
      { food: "pomme_de_terre", qty: 250, role: "glucide" },
      { food: "salade", qty: 80 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "dej-pates-thon-tomate",
    nom: "Pâtes au thon et à la tomate",
    repas: "dejeuner",
    effort: 1,
    minutes: 18,
    ingredients: [
      { food: "pates", qty: 220, role: "glucide" },
      { food: "thon", qty: 120, role: "proteine" },
      { food: "passata", qty: 150 },
      { food: "olives", qty: 30, role: "lipide" },
    ],
  },
  {
    id: "dej-pates-pesto-poulet",
    nom: "Pâtes complètes au pesto et poulet",
    repas: "dejeuner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "pates_completes", qty: 200, role: "glucide" },
      { food: "poulet", qty: 170, role: "proteine" },
      { food: "pesto", qty: 30, role: "lipide" },
      { food: "tomates_cerises", qty: 150 },
    ],
  },
  {
    id: "dej-riz-saute-oeuf",
    nom: "Riz sauté aux œufs et petits pois",
    repas: "dejeuner",
    effort: 1,
    minutes: 15,
    ingredients: [
      { food: "riz", qty: 250, role: "glucide" },
      { food: "oeuf", qty: 165, role: "proteine", min: 110, max: 275 },
      { food: "petit_pois", qty: 120 },
      { food: "carotte", qty: 100 },
      { food: "sauce_soja", qty: 15 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-galette-mais-haricots",
    nom: "Galettes de maïs aux haricots rouges et avocat",
    repas: "dejeuner",
    effort: 1,
    minutes: 15,
    ingredients: [
      { food: "tortilla_mais", qty: 90, role: "glucide" },
      { food: "haricots_rouges", qty: 220, role: "proteine" },
      { food: "mais", qty: 80 },
      { food: "avocat", qty: 70, role: "lipide" },
      { food: "salade", qty: 60 },
    ],
  },
  {
    id: "dej-salade-lentilles-chevre",
    nom: "Salade de lentilles, chèvre et betterave",
    repas: "dejeuner",
    effort: 0,
    minutes: 10,
    ingredients: [
      { food: "lentilles", qty: 220, role: "proteine" },
      { food: "chevre", qty: 60 },
      { food: "betterave", qty: 120, role: "glucide", min: 60, max: 220 },
      { food: "mache", qty: 60 },
      { food: "huile_colza", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "dej-dinde-hachee-patate",
    nom: "Dinde hachée, patate douce et courgettes",
    repas: "dejeuner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "dinde_hachee", qty: 180, role: "proteine" },
      { food: "patate_douce", qty: 280, role: "glucide" },
      { food: "courgette", qty: 180 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-truite-quinoa-asperges",
    nom: "Truite, quinoa et asperges vertes",
    repas: "dejeuner",
    effort: 1,
    minutes: 22,
    ingredients: [
      { food: "truite", qty: 180, role: "proteine" },
      { food: "quinoa", qty: 200, role: "glucide" },
      { food: "asperges", qty: 180 },
      { food: "citron", qty: 90 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-moules-riz",
    nom: "Moules à la tomate et riz",
    repas: "dejeuner",
    effort: 1,
    minutes: 22,
    ingredients: [
      { food: "moules", qty: 250, role: "proteine" },
      { food: "riz", qty: 220, role: "glucide" },
      { food: "tomate", qty: 150 },
      { food: "oignon", qty: 60 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-sandwich-poulet",
    nom: "Sandwich poulet et crudités",
    repas: "dejeuner",
    effort: 0,
    minutes: 8,
    ingredients: [
      { food: "pain_complet", qty: 120, role: "glucide" },
      { food: "poulet", qty: 160, role: "proteine" },
      { food: "salade", qty: 50 },
      { food: "tomate", qty: 100 },
      { food: "moutarde", qty: 15 },
    ],
  },
  {
    id: "dej-wrap-thon-houmous",
    nom: "Wrap thon et houmous",
    repas: "dejeuner",
    effort: 0,
    minutes: 8,
    ingredients: [
      { food: "tortilla", qty: 90, role: "glucide" },
      { food: "thon", qty: 120, role: "proteine" },
      { food: "concombre", qty: 100 },
      { food: "tomate", qty: 100 },
      { food: "houmous", qty: 50, role: "lipide" },
    ],
  },
  {
    id: "dej-soupe-pois-casses",
    nom: "Soupe épaisse de pois cassés au jambon",
    repas: "dejeuner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "pois_casses", qty: 250, role: "proteine" },
      { food: "jambon", qty: 80 },
      { food: "carotte", qty: 120, role: "glucide", min: 60, max: 220 },
      { food: "poireau", qty: 120 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-wrap-seitan",
    nom: "Wrap seitan et poivrons",
    repas: "dejeuner",
    effort: 1,
    minutes: 18,
    ingredients: [
      { food: "tortilla", qty: 90, role: "glucide" },
      { food: "seitan", qty: 170, role: "proteine" },
      { food: "poivron", qty: 150 },
      { food: "oignon", qty: 60 },
      { food: "sauce_soja", qty: 15 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-salade-quinoa-feta",
    nom: "Salade de quinoa, feta et concombre",
    repas: "dejeuner",
    effort: 0,
    minutes: 12,
    ingredients: [
      { food: "quinoa", qty: 220, role: "glucide" },
      { food: "feta", qty: 80, role: "proteine" },
      { food: "concombre", qty: 120 },
      { food: "tomate", qty: 120 },
      { food: "olives", qty: 30, role: "lipide" },
    ],
  },
  {
    id: "dej-poulet-semoule-legumes",
    nom: "Poulet, semoule et légumes du couscous",
    repas: "dejeuner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "poulet", qty: 170, role: "proteine" },
      { food: "semoule", qty: 220, role: "glucide" },
      { food: "courgette", qty: 150 },
      { food: "carotte", qty: 120 },
      { food: "pois_chiches", qty: 120 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "dej-saumon-riz-edamame",
    nom: "Bowl saumon, riz et edamame",
    repas: "dejeuner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "saumon", qty: 170, role: "proteine" },
      { food: "riz", qty: 220, role: "glucide" },
      { food: "edamame", qty: 100 },
      { food: "carotte", qty: 80 },
      { food: "sauce_soja", qty: 15 },
    ],
  },
  {
    id: "dej-haricots-blancs-thon",
    nom: "Salade de haricots blancs au thon",
    repas: "dejeuner",
    effort: 0,
    minutes: 10,
    ingredients: [
      { food: "haricots_blancs", qty: 250, role: "glucide" },
      { food: "thon", qty: 120, role: "proteine" },
      { food: "tomates_cerises", qty: 150 },
      { food: "roquette", qty: 50 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  // ══════════════════════════════════════════ dîner, élargissement (30)
  {
    id: "din-poulet-legumes-rotis",
    nom: "Poulet et légumes rôtis au four",
    repas: "diner",
    effort: 1,
    minutes: 35,
    ingredients: [
      { food: "poulet", qty: 180, role: "proteine" },
      { food: "butternut", qty: 250, role: "glucide" },
      { food: "courgette", qty: 180 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-colin-poireaux-riz",
    nom: "Colin aux poireaux fondants et riz",
    repas: "diner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "colin", qty: 200, role: "proteine" },
      { food: "poireau", qty: 200 },
      { food: "riz", qty: 180, role: "glucide" },
      { food: "creme_legere", qty: 40, role: "lipide" },
    ],
  },
  {
    id: "din-truite-butternut",
    nom: "Truite rôtie et purée de butternut",
    repas: "diner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "truite", qty: 180, role: "proteine" },
      { food: "butternut", qty: 300, role: "glucide" },
      { food: "epinards", qty: 150 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-omelette-champignons-pdt",
    nom: "Omelette aux champignons, pommes de terre et salade",
    repas: "diner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "oeuf", qty: 220, role: "proteine", min: 110, max: 330 },
      { food: "champignons", qty: 150 },
      { food: "pomme_de_terre", qty: 220, role: "glucide" },
      { food: "salade", qty: 70 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "din-soupe-butternut-lentilles",
    nom: "Velouté de butternut aux lentilles corail",
    repas: "diner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "butternut", qty: 350, role: "glucide" },
      { food: "lentilles_corail", qty: 80, role: "proteine" },
      { food: "lait_coco", qty: 60, role: "lipide" },
      { food: "oignon", qty: 70 },
    ],
  },
  {
    id: "din-gratin-chou-fleur-jambon",
    nom: "Gratin de chou-fleur au jambon",
    repas: "diner",
    effort: 2,
    minutes: 40,
    ingredients: [
      { food: "chou_fleur", qty: 300 },
      { food: "jambon", qty: 120, role: "proteine" },
      { food: "emmental", qty: 50, role: "lipide" },
      { food: "lait", qty: 150 },
      { food: "pomme_de_terre", qty: 200, role: "glucide" },
    ],
  },
  {
    id: "din-crevettes-courgettes",
    nom: "Poêlée de crevettes aux courgettes et riz",
    repas: "diner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "crevettes", qty: 200, role: "proteine" },
      { food: "courgette", qty: 220 },
      { food: "riz", qty: 180, role: "glucide" },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-boulettes-dinde",
    nom: "Boulettes de dinde à la tomate et pâtes",
    repas: "diner",
    effort: 2,
    minutes: 35,
    ingredients: [
      { food: "dinde_hachee", qty: 180, role: "proteine" },
      { food: "passata", qty: 200 },
      { food: "pates", qty: 200, role: "glucide" },
      { food: "oignon", qty: 70 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "din-curry-tofu-epinards",
    nom: "Curry de tofu aux épinards",
    repas: "diner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "tofu", qty: 200, role: "proteine" },
      { food: "epinards", qty: 150 },
      { food: "riz", qty: 200, role: "glucide" },
      { food: "lait_coco", qty: 60, role: "lipide" },
      { food: "tomates_concassees", qty: 150 },
    ],
  },
  {
    id: "din-salade-tiede-pois-chiches",
    nom: "Salade tiède de pois chiches rôtis et feta",
    repas: "diner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "pois_chiches", qty: 250, role: "glucide" },
      { food: "feta", qty: 80, role: "proteine" },
      { food: "poivron", qty: 150 },
      { food: "roquette", qty: 60 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-cabillaud-fenouil",
    nom: "Cabillaud au fenouil et pommes de terre",
    repas: "diner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "cabillaud", qty: 200, role: "proteine" },
      { food: "fenouil", qty: 200 },
      { food: "pomme_de_terre", qty: 250, role: "glucide" },
      { food: "huile_olive", qty: 12, role: "lipide" },
      { food: "citron", qty: 90 },
    ],
  },
  {
    id: "din-poelee-haricots-blancs",
    nom: "Poêlée de haricots blancs aux légumes d'été",
    repas: "diner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "haricots_blancs", qty: 250, role: "proteine" },
      { food: "riz", qty: 180, role: "glucide" },
      { food: "tomates_concassees", qty: 200 },
      { food: "courgette", qty: 180 },
      { food: "aubergine", qty: 180 },
      { food: "huile_olive", qty: 14, role: "lipide" },
    ],
  },
  {
    id: "din-frittata-courgettes",
    nom: "Frittata courgettes et chèvre",
    repas: "diner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "oeuf", qty: 220, role: "proteine", min: 110, max: 330 },
      { food: "courgette", qty: 200 },
      { food: "chevre", qty: 60 },
      { food: "pomme_de_terre", qty: 200, role: "glucide" },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-saumon-polenta",
    nom: "Saumon, polenta crémeuse et épinards",
    repas: "diner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "saumon", qty: 170, role: "proteine" },
      { food: "polenta", qty: 250, role: "glucide" },
      { food: "epinards", qty: 150 },
      { food: "parmesan", qty: 25, role: "lipide" },
    ],
  },
  {
    id: "din-veloute-brocoli-oeuf",
    nom: "Velouté de brocoli et œuf poché",
    repas: "diner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "brocoli", qty: 300 },
      { food: "pomme_de_terre", qty: 250, role: "glucide" },
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 220 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-poulet-endives",
    nom: "Poulet et endives braisées gratinées",
    repas: "diner",
    effort: 2,
    minutes: 40,
    ingredients: [
      { food: "poulet", qty: 170, role: "proteine" },
      { food: "endive", qty: 250 },
      { food: "emmental", qty: 40, role: "lipide" },
      { food: "pomme_de_terre", qty: 220, role: "glucide" },
    ],
  },
  {
    id: "din-nouilles-tofu-champignons",
    nom: "Nouilles de riz sautées au tofu et champignons",
    repas: "diner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "nouilles_riz", qty: 250, role: "glucide" },
      { food: "tofu", qty: 180, role: "proteine" },
      { food: "chou_rouge", qty: 100 },
      { food: "champignons", qty: 150 },
      { food: "sauce_soja", qty: 18 },
      { food: "huile_colza", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "din-maquereau-lentilles",
    nom: "Maquereau et lentilles à la moutarde",
    repas: "diner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "maquereau", qty: 160, role: "proteine" },
      { food: "lentilles", qty: 250, role: "glucide" },
      { food: "oignon_rouge", qty: 60 },
      { food: "moutarde", qty: 15 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-risotto-quinoa-champignons",
    nom: "Risotto de quinoa aux champignons",
    repas: "diner",
    effort: 2,
    minutes: 30,
    ingredients: [
      { food: "quinoa", qty: 220, role: "glucide" },
      { food: "champignons", qty: 200 },
      { food: "ricotta", qty: 120, role: "proteine", max: 300 },
      { food: "parmesan", qty: 25, role: "lipide" },
      { food: "oignon", qty: 70 },
      { food: "huile_olive", qty: 10 },
    ],
  },
  {
    id: "din-minestrone",
    nom: "Minestrone aux haricots blancs",
    repas: "diner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "haricots_blancs", qty: 220, role: "proteine" },
      { food: "pates", qty: 120, role: "glucide" },
      { food: "carotte", qty: 120 },
      { food: "courgette", qty: 150 },
      { food: "passata", qty: 200 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-aubergines-farcies",
    nom: "Aubergines farcies à la viande",
    repas: "diner",
    effort: 2,
    minutes: 45,
    ingredients: [
      { food: "aubergine", qty: 300 },
      { food: "steak_hache", qty: 150, role: "proteine" },
      { food: "passata", qty: 150 },
      { food: "riz", qty: 150, role: "glucide" },
      { food: "emmental", qty: 30, role: "lipide" },
    ],
  },
  {
    id: "din-poulet-champignons-creme",
    nom: "Poulet aux champignons et riz",
    repas: "diner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "poulet", qty: 180, role: "proteine" },
      { food: "champignons", qty: 200 },
      { food: "creme_legere", qty: 50, role: "lipide" },
      { food: "riz", qty: 200, role: "glucide" },
    ],
  },
  {
    id: "din-galettes-pois-chiches",
    nom: "Galettes de pois chiches et salade",
    repas: "diner",
    effort: 2,
    minutes: 30,
    ingredients: [
      { food: "pois_chiches", qty: 250, role: "glucide" },
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 165 },
      { food: "salade", qty: 80 },
      { food: "tomate", qty: 120 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-colin-tomates-olives",
    nom: "Colin aux tomates et olives",
    repas: "diner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "colin", qty: 200, role: "proteine" },
      { food: "tomate", qty: 200 },
      { food: "olives", qty: 40, role: "lipide" },
      { food: "pomme_de_terre", qty: 250, role: "glucide" },
      { food: "huile_olive", qty: 10 },
    ],
  },
  {
    id: "din-wok-boeuf-legumes",
    nom: "Wok de bœuf aux légumes et nouilles",
    repas: "diner",
    effort: 1,
    minutes: 20,
    ingredients: [
      { food: "boeuf", qty: 160, role: "proteine" },
      { food: "poivron", qty: 150 },
      { food: "champignons", qty: 120 },
      { food: "nouilles_riz", qty: 220, role: "glucide" },
      { food: "sauce_soja", qty: 18 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "din-dahl-millet",
    nom: "Dahl de lentilles aux épinards et millet",
    repas: "diner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "lentilles", qty: 250, role: "proteine" },
      { food: "millet", qty: 200, role: "glucide" },
      { food: "epinards", qty: 150 },
      { food: "tomates_concassees", qty: 150 },
      { food: "huile_colza", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-pizza-pita",
    nom: "Pizza express sur pain pita",
    repas: "diner",
    effort: 1,
    minutes: 15,
    ingredients: [
      { food: "pain_pita", qty: 120, role: "glucide" },
      { food: "passata", qty: 100 },
      { food: "mozzarella", qty: 100, role: "proteine" },
      { food: "poivron", qty: 120 },
      { food: "olives", qty: 30, role: "lipide" },
    ],
  },
  {
    id: "din-poulet-curry-coco",
    nom: "Poulet au curry et lait de coco",
    repas: "diner",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "poulet", qty: 180, role: "proteine" },
      { food: "riz", qty: 200, role: "glucide" },
      { food: "lait_coco", qty: 70, role: "lipide" },
      { food: "poivron", qty: 150 },
    ],
  },
  {
    id: "din-salade-betterave-oeuf",
    nom: "Salade de betterave, œuf dur et mâche",
    repas: "diner",
    effort: 0,
    minutes: 12,
    ingredients: [
      { food: "betterave", qty: 180 },
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 220 },
      { food: "mache", qty: 70 },
      { food: "pomme_de_terre", qty: 220, role: "glucide" },
      { food: "huile_colza", qty: 14, role: "lipide" },
    ],
  },
  {
    id: "din-curry-pois-chiches-butternut",
    nom: "Curry de pois chiches et butternut",
    repas: "diner",
    effort: 1,
    minutes: 30,
    ingredients: [
      { food: "pois_chiches", qty: 250, role: "proteine" },
      { food: "butternut", qty: 250 },
      { food: "riz", qty: 180, role: "glucide" },
      { food: "lait_coco", qty: 60, role: "lipide" },
      { food: "epinards", qty: 120 },
    ],
  },
  // ═══════════════════════════════════════ collation, élargissement (22)
  {
    id: "col-fromage-blanc-framboises",
    nom: "Fromage blanc, framboises et graines de lin",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "fromage_blanc", qty: 220, role: "proteine" },
      { food: "framboises", qty: 100 },
      { food: "miel", qty: 12, role: "glucide" },
      { food: "graines_lin", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "col-pomme-cacahuete",
    nom: "Pomme et beurre de cacahuète",
    repas: "collation",
    effort: 0,
    minutes: 2,
    ingredients: [
      { food: "pomme", qty: 180, role: "glucide" },
      { food: "beurre_cacahuete", qty: 30, role: "proteine", min: 20, max: 35 },
    ],
  },
  {
    id: "col-yaourt-soja-dattes",
    nom: "Yaourt de soja, dattes et noix de cajou",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "yaourt_soja", qty: 180 },
      { food: "proteine_pois", qty: 20, role: "proteine", max: 35 },
      { food: "dattes", qty: 40, role: "glucide" },
      { food: "noix_cajou", qty: 20, role: "lipide" },
    ],
  },
  {
    id: "col-tartine-banane-tahini",
    nom: "Tartine banane et purée de sésame",
    repas: "collation",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "pain_complet", qty: 70, role: "glucide" },
      { food: "banane", qty: 120 },
      { food: "tahini", qty: 20, role: "proteine", min: 10, max: 40 },
    ],
  },
  {
    id: "col-shake-vegetal-banane",
    nom: "Shake protéiné végétal à la banane",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "proteine_pois", qty: 30, role: "proteine" },
      { food: "banane", qty: 150, role: "glucide" },
      { food: "boisson_soja", qty: 250, min: 150, max: 400 },
    ],
  },
  {
    id: "col-cottage-fruits-secs",
    nom: "Cottage cheese, raisins secs et graines de courge",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "cottage", qty: 200, role: "proteine" },
      { food: "raisins_secs", qty: 30, role: "glucide" },
      { food: "graines_courge", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "col-thon-galettes-riz",
    nom: "Galettes de riz au thon",
    repas: "collation",
    effort: 0,
    minutes: 5,
    ingredients: [
      { food: "galette_riz", qty: 27, role: "glucide", min: 9, max: 72 },
      { food: "thon", qty: 100, role: "proteine" },
      { food: "tomate", qty: 100 },
      { food: "avocat", qty: 40, role: "lipide" },
    ],
  },
  {
    id: "col-houmous-crudites",
    nom: "Houmous et crudités",
    repas: "collation",
    effort: 0,
    minutes: 6,
    ingredients: [
      { food: "houmous", qty: 80, role: "proteine", min: 50, max: 100 },
      { food: "carotte", qty: 120 },
      { food: "concombre", qty: 120 },
      { food: "pain_pita", qty: 60, role: "glucide" },
      { food: "huile_olive", qty: 5, role: "lipide", min: 3, max: 12 },
    ],
  },
  {
    id: "col-skyr-cacao-noisettes",
    nom: "Skyr au cacao et noisettes",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "skyr", qty: 200, role: "proteine" },
      { food: "cacao", qty: 8 },
      { food: "miel", qty: 15, role: "glucide" },
      { food: "noisettes", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "col-smoothie-mangue-coco",
    nom: "Smoothie mangue et coco",
    repas: "collation",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "mangue", qty: 150, role: "glucide" },
      { food: "yaourt_coco", qty: 120, role: "lipide", min: 60, max: 200 },
      { food: "proteine_pois", qty: 25, role: "proteine" },
      { food: "banane", qty: 100 },
    ],
  },
  {
    id: "col-edamame",
    nom: "Edamame et galettes de riz",
    repas: "collation",
    effort: 1,
    minutes: 8,
    ingredients: [
      { food: "edamame", qty: 150, role: "proteine" },
      { food: "galette_riz", qty: 18, role: "glucide", min: 9, max: 45 },
      { food: "huile_olive", qty: 5, role: "lipide", min: 3, max: 12 },
    ],
  },
  {
    id: "col-oeuf-dur-tartine",
    nom: "Œuf dur et tartine de tomate",
    repas: "collation",
    effort: 1,
    minutes: 12,
    ingredients: [
      { food: "oeuf", qty: 110, role: "proteine", min: 55, max: 165 },
      { food: "pain_complet", qty: 60, role: "glucide" },
      { food: "tomate", qty: 100 },
    ],
  },
  {
    id: "col-fromage-blanc-poire",
    nom: "Fromage blanc, poire et flocons d'avoine",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "fromage_blanc", qty: 220, role: "proteine" },
      { food: "poire", qty: 170 },
      { food: "avoine", qty: 30, role: "glucide" },
      { food: "miel", qty: 10 },
    ],
  },
  {
    id: "col-barres-dattes-avoine",
    nom: "Barres maison dattes, avoine et cacao",
    repas: "collation",
    effort: 1,
    minutes: 15,
    ingredients: [
      { food: "dattes", qty: 60, role: "glucide", min: 24, max: 110 },
      { food: "avoine", qty: 25 },
      { food: "beurre_cacahuete", qty: 30, role: "proteine", min: 15, max: 45 },
      { food: "cacao", qty: 8 },
    ],
  },
  {
    id: "col-crackers-chevre-raisin",
    nom: "Pain sans gluten, chèvre frais et raisin",
    repas: "collation",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "pain_sans_gluten", qty: 70, role: "glucide" },
      { food: "chevre", qty: 60, role: "proteine" },
      { food: "raisin", qty: 100 },
    ],
  },
  {
    id: "col-compote-son-avoine",
    nom: "Compote, son d'avoine et fromage blanc",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "compote", qty: 150 },
      { food: "son_avoine", qty: 30, role: "glucide" },
      { food: "fromage_blanc", qty: 200, role: "proteine" },
      { food: "graines_lin", qty: 10, role: "lipide", min: 5, max: 20 },
    ],
  },
  {
    id: "col-tomate-mozzarella",
    nom: "Tomates cerises, mozzarella et pain",
    repas: "collation",
    effort: 0,
    minutes: 5,
    ingredients: [
      { food: "mozzarella", qty: 100, role: "proteine" },
      { food: "tomates_cerises", qty: 150 },
      { food: "olives", qty: 25, role: "lipide" },
      { food: "pain_complet", qty: 60, role: "glucide" },
    ],
  },
  {
    id: "col-smoothie-kefir-fraises",
    nom: "Smoothie kéfir et fraises",
    repas: "collation",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "kefir", qty: 200 },
      { food: "skyr", qty: 120, role: "proteine", max: 250 },
      { food: "fraises", qty: 150 },
      { food: "avoine", qty: 30, role: "glucide" },
    ],
  },
  {
    id: "col-abricots-cacahuetes",
    nom: "Abricots secs, cacahuètes et pomme",
    repas: "collation",
    effort: 0,
    minutes: 2,
    ingredients: [
      { food: "abricots_secs", qty: 50, role: "glucide" },
      { food: "cacahuetes", qty: 30, role: "proteine", min: 20, max: 35 },
      { food: "pomme", qty: 150 },
    ],
  },
  {
    id: "col-pois-chiches-rotis",
    nom: "Pois chiches rôtis au paprika",
    repas: "collation",
    effort: 1,
    minutes: 25,
    ingredients: [
      { food: "pois_chiches", qty: 200, role: "proteine" },
      { food: "galette_riz", qty: 18, role: "glucide", min: 9, max: 45 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "col-graines-courge-raisins",
    nom: "Graines de courge, raisins secs et pomme",
    repas: "collation",
    effort: 0,
    minutes: 2,
    ingredients: [
      { food: "graines_courge", qty: 30, role: "proteine", min: 20, max: 35 },
      { food: "raisins_secs", qty: 35, role: "glucide" },
      { food: "pomme", qty: 150 },
    ],
  },
  {
    id: "col-yaourt-grec-miel-fruits",
    nom: "Yaourt grec, miel et fruits rouges",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "yaourt_grec", qty: 200, role: "proteine" },
      { food: "myrtilles", qty: 100 },
      { food: "miel", qty: 15, role: "glucide" },
      { food: "graines_tournesol", qty: 12, role: "lipide" },
    ],
  },
  // ═══════════════ couverture des profils contraints (sans cuisson, végétal)
  {
    id: "dej-salade-pois-chiches-crudites",
    nom: "Salade de pois chiches et crudités",
    repas: "dejeuner",
    effort: 0,
    minutes: 10,
    ingredients: [
      { food: "pois_chiches", qty: 250, role: "proteine" },
      { food: "mais", qty: 120, role: "glucide" },
      { food: "concombre", qty: 120 },
      { food: "tomates_cerises", qty: 150 },
      { food: "huile_olive", qty: 14, role: "lipide" },
    ],
  },
  {
    id: "dej-wrap-houmous-vegan",
    nom: "Wrap houmous et pois chiches",
    repas: "dejeuner",
    effort: 0,
    minutes: 8,
    ingredients: [
      { food: "tortilla", qty: 90, role: "glucide" },
      { food: "pois_chiches", qty: 180, role: "proteine" },
      { food: "houmous", qty: 60, role: "lipide" },
      { food: "carotte", qty: 100 },
      { food: "salade", qty: 60 },
    ],
  },
  {
    id: "dej-salade-haricots-rouges",
    nom: "Salade mexicaine haricots rouges et avocat",
    repas: "dejeuner",
    effort: 0,
    minutes: 10,
    ingredients: [
      { food: "haricots_rouges", qty: 250, role: "proteine" },
      { food: "mais", qty: 120, role: "glucide" },
      { food: "poivron", qty: 120 },
      { food: "avocat", qty: 70, role: "lipide" },
      { food: "oignon_rouge", qty: 40 },
    ],
  },
  {
    id: "din-salade-lentilles-betterave",
    nom: "Salade de lentilles, betterave et graines",
    repas: "diner",
    effort: 0,
    minutes: 10,
    ingredients: [
      { food: "lentilles", qty: 250, role: "proteine" },
      { food: "mais", qty: 100, role: "glucide" },
      { food: "betterave", qty: 120 },
      { food: "tomates_cerises", qty: 150 },
      { food: "graines_courge", qty: 20, role: "lipide" },
    ],
  },
  {
    id: "din-assiette-mezze",
    nom: "Assiette mezze aux haricots blancs",
    repas: "diner",
    effort: 0,
    minutes: 12,
    ingredients: [
      { food: "haricots_blancs", qty: 250, role: "proteine" },
      { food: "pain_pita", qty: 100, role: "glucide" },
      { food: "houmous", qty: 60, role: "lipide" },
      { food: "concombre", qty: 120 },
      { food: "tomate", qty: 120 },
      { food: "olives", qty: 30 },
    ],
  },
  {
    id: "din-salade-quinoa-pois-chiches",
    nom: "Salade de quinoa, pois chiches et roquette",
    repas: "diner",
    effort: 0,
    minutes: 12,
    ingredients: [
      { food: "quinoa", qty: 220, role: "glucide" },
      { food: "pois_chiches", qty: 220, role: "proteine" },
      { food: "tomates_cerises", qty: 150 },
      { food: "roquette", qty: 60 },
      { food: "huile_olive", qty: 14, role: "lipide" },
    ],
  },
  {
    id: "din-assiette-saumon-fume",
    nom: "Assiette saumon fumé, chèvre frais et concombre",
    repas: "diner",
    effort: 0,
    minutes: 10,
    ingredients: [
      { food: "saumon_fume", qty: 100 },
      { food: "pain_complet", qty: 100, role: "glucide" },
      { food: "chevre", qty: 80, role: "proteine" },
      { food: "concombre", qty: 150 },
      { food: "huile_olive", qty: 10, role: "lipide" },
    ],
  },
  {
    id: "din-salade-poulet-riz",
    nom: "Salade de riz au poulet et poivrons",
    repas: "diner",
    effort: 0,
    minutes: 12,
    ingredients: [
      { food: "poulet", qty: 170, role: "proteine" },
      { food: "riz", qty: 220, role: "glucide" },
      { food: "poivron", qty: 120 },
      { food: "mais", qty: 100 },
      { food: "huile_olive", qty: 12, role: "lipide" },
    ],
  },
  {
    id: "din-salade-thon-pdt",
    nom: "Salade de pommes de terre au thon",
    repas: "diner",
    effort: 0,
    minutes: 12,
    ingredients: [
      { food: "thon", qty: 120, role: "proteine" },
      { food: "pomme_de_terre", qty: 280, role: "glucide" },
      { food: "haricots_verts", qty: 150 },
      { food: "tomate", qty: 120 },
      { food: "olives", qty: 30, role: "lipide" },
    ],
  },
  {
    id: "pdj-bol-riz-fruits",
    nom: "Bol de riz aux fruits et graines de courge",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 5,
    ingredients: [
      { food: "riz", qty: 200, role: "glucide" },
      { food: "proteine_pois", qty: 25, role: "proteine" },
      { food: "banane", qty: 120 },
      { food: "graines_courge", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "pdj-compote-galettes",
    nom: "Galettes de riz, compote et graines de tournesol",
    repas: "petit-dejeuner",
    effort: 0,
    minutes: 4,
    ingredients: [
      { food: "galette_riz", qty: 27, role: "glucide", min: 9, max: 63 },
      { food: "compote", qty: 150 },
      { food: "proteine_pois", qty: 25, role: "proteine" },
      { food: "graines_tournesol", qty: 15, role: "lipide" },
    ],
  },
  {
    id: "col-banane-tournesol",
    nom: "Banane, compote et graines de tournesol",
    repas: "collation",
    effort: 0,
    minutes: 2,
    ingredients: [
      { food: "banane", qty: 150, role: "glucide" },
      { food: "graines_tournesol", qty: 30, role: "proteine", min: 20, max: 35 },
      { food: "compote", qty: 100 },
    ],
  },
  {
    id: "col-yaourt-coco-fruits-rouges",
    nom: "Yaourt de coco et fruits rouges",
    repas: "collation",
    effort: 0,
    minutes: 3,
    ingredients: [
      { food: "yaourt_coco", qty: 130, role: "lipide", min: 70, max: 200 },
      { food: "fraises", qty: 120 },
      { food: "proteine_pois", qty: 20, role: "proteine", min: 12, max: 30 },
      { food: "miel", qty: 12, role: "glucide" },
    ],
  },
];
