import type { Feature, LandingCopy, Overrides } from "./coach-copy";

// Textes de vente des landings pro->client, en allemand. Même structure que
// le français : un socle, et les remplacements pour une salle.

export const DE: Omit<LandingCopy, "features"> & { features: Feature[] } = {
  defaultTagline:
    "Ein Programm, entworfen von deinem Coach nach seiner Methode, angepasst an dein Studio und deine Vorgaben, und täglich begleitet. Unterstützt von einer KI-Engine, spezialisiert auf körperliche Transformation.",
  login: "Anmelden",
  seePrograms: "Programme ansehen",
  howItWorks: "So funktioniert es",
  heroChip: "Persönliches Coaching",
  heroChecks: ["Programm mit der Handschrift deines Coachs", "Gesundheit und Allergien berücksichtigt", "Tägliche Begleitung"],
  stats: [
    { v: "Dein Coach", l: "entwirft deine Methode" },
    { v: "100 %", l: "angepasst an dein Studio & deine Gesundheit" },
    { v: "KI-Engine", l: "im Dienst seiner Methode" },
    { v: "Maßgeschneidert", l: "einzeln oder im Abo" },
  ],
  featuresChip: "Funktionen",
  featuresTitle: "Alles, was du zum Erfolg brauchst",
  features: [
    { title: "Die Methode deines Coachs", body: "Dein Programm baut auf der Methode deines Coachs: Übungen, Sätze, Gewichte und Progressionen, von ihm durchdacht." },
    { title: "Analyse deines Studios", body: "Fotografiere deine Geräte: Der Plan nutzt nur die wirklich verfügbare Ausstattung." },
    { title: "100 % personalisiert", body: "Beschwerden, Allergien, Ernährungsweise, religiöser Rahmen: Jede Vorgabe wird berücksichtigt." },
    { title: "Eine Engine, kein Pilot", body: "Dein Coach behält jede Entscheidung in der Hand. Die KI-Engine hilft ihm, seine Methode lückenlos auf deinen Fall anzuwenden." },
    { title: "Präzise Herzfrequenzzonen", body: "Deine Intensitätszonen, berechnet, um aus jeder Cardio-Einheit das Beste herauszuholen." },
    { title: "Kompletter Kundenbereich", body: "Interaktive Trainings, Kalender, Ernährungstagebuch per Barcode-Scan, Gewichtskurve: dein ganzer Verlauf an einem Ort." },
    { title: "Trainingswerkzeuge", body: "Integrierter Pausen-Timer, Tagebuch Satz für Satz (kg × Wdh.), Fortschritt und Häkchen." },
    { title: "Ein von deinem Coach geschulter Assistent", body: "Ein ständig verfügbarer Assistent, trainiert auf die Methode deines Coachs. Er antwortet, motiviert und begleitet dich im Alltag." },
  ],
  gymChip: "Dein Studio, deine Ausstattung",
  gymTitle: "Dein Studio analysiert. Dein Programm angepasst.",
  gymBody: "Fotografiere dein Studio: Die KI erkennt die verfügbare Ausstattung und stellt sicher, dass jede Übung deines Programms mit dem machbar ist, was du hast.",
  gymBullets: ["Kurzhanteln, Langhanteln, Kabelzüge, geführte Maschinen", "Home-Gym mit begrenzter Ausstattung", "Gemeinschaftsraum oder Hotel", "Training nur mit Körpergewicht"],
  gymScanLabel: "KI analysiert, Ausstattung erkannt",
  spaceChip: "Kundenbereich",
  spaceTitle: "Dein Programm, jeden Tag lebendig.",
  spaceBody: "Mehr als ein Dokument: Dein Programm ist interaktiv. Hake deine Übungen ab, starte deinen Timer, sieh deine Ernährung ein und sprich mit deinem KI-Coach.",
  spaceBullets: ["Interaktive Trainings", "Checkliste der Übungen", "Stoppuhr & Timer", "Ernährung des Tages", "Fortschrittsverlauf", "KI-Assistent mit einem Tipp"],
  nutritionChip: "Ernährung",
  nutritionTitle: "Eine Ernährung, so präzise wie dein Training.",
  nutritionBody: "Kalorien, Makros, Timing der Mahlzeiten und passende Rezepte. Deine Allergien, Unverträglichkeiten und dein religiöser Rahmen (halal, koscher, vegetarisch…) werden berücksichtigt. Und um zu wissen, wo du stehst: Du scannst den Barcode von dem, was du isst, Kalorien und Makros füllen sich von selbst, neben deinem Tagesziel.",
  nutritionBullets: ["Barcode-Scan", "Tagebuch neben deinem Ziel", "Halal / koscher", "Vegetarisch / vegan", "Allergien und Unverträglichkeiten", "Rezepte pro Woche"],
  stepsTitle: "3 Schritte zu deiner Transformation",
  steps: [
    { k: "01", title: "Beantworte den Fragebogen", body: "Ziele, Niveau, Verfügbarkeit, Gesundheit, Allergien und Ernährungsvorlieben." },
    { k: "02", title: "Fotografiere dein Studio", body: "Das System liest die verfügbare Ausstattung, um jede Übung an das anzupassen, was du hast." },
    { k: "03", title: "Folge deinem Programm", body: "Dein Plan wartet in deinem Kundenbereich, Training für Training, Tag für Tag." },
  ],
  forWhoTitle: "Ist das etwas für dich?",
  forWho: [
    { title: "Vom Anfänger bis zum Fortgeschrittenen", body: "Als Anfänger bauen wir Technik und Gewohnheit auf; als Fortgeschrittener suchen wir Überlastung und Leistung. Das Programm richtet sich nach deinem Niveau." },
    { title: "Eine gesundheitliche Einschränkung", body: "Gesundheitscheck zu Beginn, angepasste Übungen, ärztliche Freigabe bei Bedarf." },
    { title: "Allergien, vegetarisch, halal, koscher", body: "Deine Ernährungsvorgaben werden in der gesamten Ernährung respektiert." },
    { title: "Wenig Zeit", body: "Du wählst deine Tage; die Trainings sind auf deine Realität kalibriert." },
    { title: "Studio oder zu Hause", body: "Wir nutzen nur deine Ausstattung, wo auch immer du trainierst." },
    { title: "Wiedereinstieg nach einer Pause", body: "Der Anpassungszyklus bringt dich wieder in Gang, ohne dich zu verheizen." },
  ],
  aboutChip: "Über mich",
  authorChip: "Wer dein Programm entwirft",
  authorTitle: "Dein Coach schreibt dein Programm. Kein Roboter.",
  authorBody:
    "Die Übungen, die Reihenfolge der Trainings, die Startgewichte, das Tempo der Progression: Alles kommt aus der Methode deines Coachs, aus dem, was er in der Praxis mit seinen Kunden gelernt hat. Nichts stammt aus einem generischen Katalog.",
  authorPoints: [
    { title: "Seine Methode, schwarz auf weiß", body: "Dein Coach hat seine Arbeitsweise festgehalten: seine Prinzipien, seine Lieblingsübungen, seine Progressionen, was er nicht machen lässt. Dein Programm hält sich daran." },
    { title: "Seine Entscheidungen, keine Durchschnittswerte", body: "Zwei Personen mit demselben Ziel bekommen nicht denselben Plan. Das Urteil deines Coachs über deinen Fall entscheidet." },
    { title: "Er bleibt erreichbar", body: "Ein Programm ist kein PDF, das man dir schickt und vergisst. Dein Coach verfolgt, was du tust, und passt an." },
  ],
  authorSignature: (name) => `Programme mit der Handschrift von ${name}`,
  engineChip: "Die Engine dahinter",
  engineTitle: "Eine Engine, spezialisiert auf körperliche Transformation.",
  engineBody:
    "Um seine Methode auf deinen konkreten Fall anzuwenden, stützt sich dein Coach auf eine KI-Engine, die für eine einzige Sache trainiert wurde: Trainings- und Ernährungspläne zu bauen. Das ist kein generischer Assistent, den man nach dem Wetter fragt.",
  enginePoints: [
    { title: "Was Stunden dauerte, dauert Minuten", body: "Dein Ziel, dein Niveau, deine verfügbaren Tage, deine Ausstattung, deine gesundheitlichen Vorgaben und deine Ernährungsverbote zusammenzubringen: Die Engine übernimmt diese Zusammenstellung, damit dein Coach seine Zeit für Entscheidungen nutzt, nicht für die Formatierung." },
    { title: "Nichts geht unterwegs verloren", body: "Eine im Fragebogen angegebene Allergie findet sich in jedem Rezept der zwölf Wochen wieder. Eine schmerzende Schulter schließt die betroffenen Übungen im ganzen Plan aus, nicht nur in der ersten Woche." },
    { title: "Dein Plan lernt weiter", body: "Die Gewichte, die du einträgst, die Trainings, die du auslässt, dein Gewicht, das sich bewegt: Der nächste Block wird auf dem aufgebaut, was du wirklich gemacht hast, nicht auf dem, was geplant war." },
    { title: "Ein Ansprechpartner zu jeder Stunde", body: "Der KI-Coach übernimmt die Methode deines Coachs, um sonntags um 23 Uhr zu antworten, wenn eine Maschine besetzt ist oder eine Mahlzeit nicht passt. Dein Coach muss dafür nicht wach sein." },
  ],
  engineLimit:
    "Die Engine entscheidet nicht anstelle deines Coachs: Sie wendet seine Methode an. Und sie ersetzt weder einen ärztlichen Rat noch den Blick eines Profis auf deine Technik.",
  navMethod: "Die Methode",
  navPrograms: "Programme",
  navFaq: "Fragen",
  leadPoints: [
    "Eine komplette Woche, Tag für Tag",
    "Zielgewichte und technische Hinweise",
    "Ernährung in Zahlen und Einkaufsliste",
    "Verlaufstabelle zum Ausdrucken",
  ],
  leadReassure: "Ohne Bindung, ohne Kreditkarte",
  testimonialsTitle: "Was seine Kunden sagen",
  leadChip: "Geschenkt",
  leadTitle: "Deine erste Woche, geschenkt",
  heroLead: "Meine erste Woche, geschenkt",
  leadBody: "Ein echter Plan zum Befolgen, kalibriert auf dein Ziel, dein Niveau und deine Ausstattung. Bereit zum Drucken.",
  leadCta: "Mein Programm erhalten",
  programsChip: "Programme",
  programsTitle: "Wähle dein Programm",
  noOffer: "Derzeit kein Angebot verfügbar. Schau bald wieder vorbei.",
  giftTitle: "Lust, jemandem eine Freude zu machen?",
  giftBody: "Schenke jemandem ein Programm: Du zahlst, die Person bekommt einen Code, den sie frei einlösen kann.",
  giftCta: "Ich möchte ein Programm verschenken",
  faqChip: "FAQ",
  faqTitle: "Häufige Fragen",
  faqs: [
    { q: "Braucht es ein Studio oder besondere Ausstattung?", a: "Nein. Du fotografierst, was du hast, komplettes Studio, Home-Gym oder ein paar Kurzhanteln, und das Programm wird ausschließlich mit dieser Ausstattung gebaut." },
    { q: "Ich bin Anfänger, ist das geeignet?", a: "Ja. Der Anfang des Programms ist der Technik und dem Aufbau der Gewohnheit gewidmet. Danach steigern wir uns schrittweise." },
    { q: "Wie läuft die Zahlung ab?", a: "Die Zahlung ist über Stripe gesichert, direkt bei deinem Coach. Je nach gewähltem Programm ist es eine Einmalzahlung oder ein Abo (monatlich oder jährlich), jederzeit aus deinem Bereich kündbar." },
    { q: "Wer entwirft das Programm wirklich?", a: "Dein Coach. Das Programm baut auf SEINER Methode; er stützt sich auf eine KI, die er auf seine Arbeitsweise trainiert hat. Der KI-Assistent verlängert diese Begleitung im Alltag, ersetzt aber weder deinen Coach noch einen ärztlichen Rat." },
    { q: "Ich habe eine Verletzung, eine Erkrankung oder bin schwanger?", a: "Ein Gesundheitscheck zu Beginn erkennt Risikosituationen. Das Programm wird angepasst oder pausiert, bis dein Arzt grünes Licht gibt." },
    { q: "3 Monate oder 12 Monate, was ist der Unterschied?", a: "Die 3 Monate sind ein Sprint mit Ziellinie: 3 Zyklen mit steigender Intensität, für ein sichtbares Ergebnis in 12 Wochen. Die 12 Monate sind ein Programm, das von dir lernt: 4 Blöcke à 3 Monate, jeder auf dem aufgebaut, was du im vorherigen wirklich gemacht hast, mit einem Schwerpunkt, der im Laufe des Jahres wechselt (Grundlagen, Volumen, Kraft, Peak)." },
    { q: "Was passiert nach dem Programm?", a: "Der KI-Coach wird am Ende deaktiviert, aber dein Plan bleibt noch eine Weile im Lesemodus einsehbar. Bei 3 Monaten schlägt dir dein Coach vor, auf 12 Monate weiterzumachen, unter Abzug dessen, was du schon gezahlt hast." },
  ],
  finalTitle: "Deine Transformation beginnt heute.",
  legalNote: "Sport- und Wohlfühlbegleitung ohne therapeutischen Anspruch. Die Ernährungsbegleitung ist eine Hilfe bei der Wahl der Mahlzeiten, keine diätetische Verordnung. Ersetzt keinen ärztlichen Rat.",
  footerLogin: "Anmelden",
  footerLegal: "Impressum",
  footerPrivacy: "Datenschutz",
  footerTerms: "AGB",
  poweredBy: "Angetrieben von",
  mostChosen: "Am häufigsten gewählt",
  oneTime: "Einmalzahlung",
  perMonthOn: (amount, months) => `das sind ${amount}/Monat über ${months} Monate`,
  choose: "Dieses Programm wählen",
  soon: "Bald verfügbar",
  payOnce: "Auf einmal",
  payInstallments: (n) => `In ${n} Raten`,
  perMonthTimes: (n) => `/Monat × ${n}`,
  autoStop: (n) => `${n} Zahlungen, dann nichts mehr: Der Stopp ist automatisch.`,
  totalOver: (amount, n) => `das sind ${amount} insgesamt über ${n} Monate`,
  mockCoach: "KI-Coach",
  mockCoachSub: "antwortet live",
  mockSession: "Training des Tages",
  mockDay: "Tag 24",
};

export const GYM_DE: Overrides = {
  testimonialsTitle: "Was seine Mitglieder sagen",
  defaultTagline:
    "Ein Programm, gebaut vom Team deines Studios, mit den Geräten, die hier stehen, und das dich auch an den Tagen begleitet, an denen du nicht kommst. Unterstützt von einer Engine, spezialisiert auf körperliche Transformation.",
  heroChip: "Programm in deiner Mitgliedschaft enthalten",
  heroChecks: ["Gebaut auf der Ausstattung des Studios", "Vom Team begleitet", "Auch an den Tagen ohne Besuch"],
  stats: [
    { v: "Unser Team", l: "entwirft dein Programm" },
    { v: "Unsere Geräte", l: "die, die du zur Hand hast" },
    { v: "7 T. / 7", l: "ein Plan auch außerhalb des Studios" },
    { v: "Ohne Aufpreis", l: "in deinem Abo enthalten" },
  ],
  featuresTitle: "Was dir deine Mitgliedschaft zusätzlich bringt",
  features: [
    { title: "Die Methode des Studios", body: "Unsere Coaches haben ihre Art, Fortschritt zu erzeugen, festgehalten: Sie baut deinen Plan, kein anderswo gekauftes Standardmodell." },
    { title: "Unsere Geräte, nicht die eines Katalogs", body: "Der Gerätepark des Studios ist bis zur letzten Station bekannt. Dein Programm schickt dich nie an ein Gerät, das wir nicht haben, oder an das, das um 18 Uhr immer besetzt ist." },
    { title: "Angepasst an dich, nicht an die Gruppe", body: "Beschwerden, Allergien, Ernährungsweise, religiöser Rahmen, Zeiten: Dein Plan berücksichtigt deine Situation, nicht den Durchschnitt der Mitglieder." },
    { title: "Eine Engine, kein Pilot", body: "Das Team behält jede Entscheidung in der Hand. Die KI-Engine hilft ihm, seine Methode lückenlos auf jedes Mitglied anzuwenden." },
    { title: "Präzise Herzfrequenzzonen", body: "Deine Intensitätszonen, berechnet, damit das Cardio im Studio wirklich etwas bringt." },
    { title: "Dein Mitgliederbereich", body: "Interaktive Trainings, Kalender, Gewichtstagebuch, Ernährungstagebuch per Barcode-Scan, Gewichtskurve: was du hier und anderswo tust, an einem Ort." },
    { title: "Trainingswerkzeuge", body: "Pausen-Timer, Tagebuch Satz für Satz, sichtbarer Fortschritt: alles, um allein zu trainieren, ohne den Faden zu verlieren." },
    { title: "Ein Ansprechpartner außerhalb der Öffnungszeiten", body: "Der KI-Coach übernimmt die Methode des Studios und antwortet, wenn der Empfang geschlossen ist, unterwegs oder im Urlaub." },
  ],
  gymChip: "Unser Gerätepark",
  gymTitle: "Unsere Geräte stehen schon in deinem Programm.",
  gymBody:
    "Wir wissen genau, was das Studio enthält. Dein Plan ist mit dieser Ausstattung geschrieben, und wenn du eine Woche lang anderswo trainierst, fotografierst du den Ort, und das Programm passt sich an.",
  gymBullets: ["Der Freihantelbereich", "Die geführten Maschinen", "Der Cardio-Bereich", "Und dein Urlaubsstudio, per Foto"],
  spaceChip: "Mitgliederbereich",
  spaceTitle: "Dein Programm begleitet dich außerhalb des Studios.",
  spaceBody:
    "Die meisten Abbrüche passieren in den Wochen, in denen man nicht kommt. Dein Mitgliederbereich sagt dir, was an diesem Tag zu tun ist, im Studio oder anderswo, und hält fest, was du gemacht hast.",
  authorChip: "Wer dein Programm entwirft",
  authorTitle: "Die Coaches des Studios. Kein Roboter.",
  authorBody:
    "Die Übungen, die Reihenfolge der Trainings, die Startgewichte, das Tempo der Progression: Alles kommt aus der Methode unseres Teams, aus dem, was es hier, auf dieser Trainingsfläche, mit unseren Mitgliedern funktionieren sieht.",
  authorPoints: [
    { title: "Eine hauseigene Methode", body: "Unsere Coaches haben ihre Arbeitsweise aufgeschrieben: ihre Prinzipien, ihre Referenzübungen, ihre Progressionen, was sie nicht machen lassen. Dein Programm hält sich daran." },
    { title: "Menschen, denen du begegnen kannst", body: "Das sind keine Programme, die bei einem fernen Dienstleister gekauft wurden. Das Team, das sie unterschreibt, ist das, das du auf der Trainingsfläche siehst." },
    { title: "Eine Brücke zwischen zwei Besuchen", body: "Was dir ein Coach im Training korrigiert hat, findet sich in deinem Wochenplan wieder, statt verloren zu gehen." },
  ],
  authorSignature: (name) => `Programme mit der Handschrift des Teams ${name}`,
  engineBody:
    "Um seine Methode auf jedes Mitglied anzuwenden, stützt sich das Team auf eine KI-Engine, die für eine einzige Sache trainiert wurde: Trainings- und Ernährungspläne zu bauen. Das ist kein generischer Assistent, den man nach dem Wetter fragt.",
  enginePoints: [
    { title: "Ein maßgeschneiderter Plan für jedes Mitglied", body: "Ein persönliches Programm pro Mitglied von Hand zu schreiben wäre im Maßstab eines Studios unmöglich. Die Engine macht es machbar, ohne in das kopierte Programm zu verfallen." },
    { title: "Nichts geht unterwegs verloren", body: "Eine bei der Anmeldung angegebene Allergie findet sich in jedem Rezept der zwölf Wochen wieder. Eine schmerzende Schulter schließt die betroffenen Übungen im ganzen Plan aus." },
    { title: "Dein Plan lernt weiter", body: "Die Gewichte, die du einträgst, die Trainings, die du auslässt, dein Gewicht, das sich bewegt: Der nächste Block wird auf dem aufgebaut, was du wirklich gemacht hast." },
    { title: "Verfügbar, wenn das Studio geschlossen ist", body: "Der KI-Coach übernimmt die Methode des Teams, um sonntags um 23 Uhr zu antworten, wenn eine Maschine besetzt ist oder eine Mahlzeit nicht passt." },
  ],
  engineLimit:
    "Die Engine entscheidet nicht anstelle unserer Coaches: Sie wendet ihre Methode an. Und sie ersetzt weder einen ärztlichen Rat noch den Blick eines Coachs auf deine Technik.",
  stepsTitle: "3 Schritte, ab heute",
  steps: [
    { k: "01", title: "Beantworte den Fragebogen", body: "Ziele, Niveau, Verfügbarkeit, Gesundheit, Allergien und Ernährungsvorlieben. Zehn Minuten, einmal." },
    { k: "02", title: "Dein Plan wird auf unserem Gerätepark gebaut", body: "Die Ausstattung des Studios ist schon bekannt. Du fotografierst nur, wenn du anderswo trainierst." },
    { k: "03", title: "Trainiere, hier und anderswo", body: "Dein Mitgliederbereich sagt dir jeden Tag, was zu tun ist, und hält fest, was du machst." },
  ],
  forWhoTitle: "Für welches Mitglied?",
  forWho: [
    { title: "Wer sich im Kreis dreht", body: "Du kommst regelmäßig, machst aber seit Monaten dieselben Maschinen. Wir geben dir eine geschriebene Progression." },
    { title: "Wer gerade angefangen hat", body: "Du weißt nicht, wo du auf der Trainingsfläche anfangen sollst. Der Plan sagt dir, was zu tun ist, in welcher Reihenfolge, mit welchem Gewicht." },
    { title: "Wer im Winter abspringt", body: "Die Wochen, in denen du nicht kommst, sind keine verlorenen Wochen mehr: Der Plan begleitet dich zu Hause." },
    { title: "Wer eine gesundheitliche Einschränkung hat", body: "Gesundheitscheck zu Beginn, angepasste Übungen, ärztliche Freigabe bei Bedarf." },
    { title: "Wer reist", body: "Ein Foto des Hotel-Fitnessraums reicht, um die Woche anzupassen." },
    { title: "Wer Ernährung will", body: "Nicht nur Training: Kalorien, Makros und Rezepte, die deine Vorgaben berücksichtigen." },
  ],
  leadTitle: "Nimm eine geschenkte Woche mit",
  heroLead: "Eine geschenkte Woche, zum Anfangen",
  leadBody: "Ein echter Plan zum Befolgen, kalibriert auf dein Ziel und auf die Ausstattung, die du hast. Bereit zum Drucken.",
  programsTitle: "Unsere Pakete",
  finalTitle: "Dein Studio. Dein Programm. Ab dem nächsten Training.",
  giftTitle: "Lust zu verschenken?",
  giftBody: "Schenke jemandem eine Begleitung: Du zahlst, die Person bekommt einen Code, den sie frei einlösen kann.",
};
