import type { Feature, LandingCopy, Overrides } from "./coach-copy";

// Textes de vente des landings pro->client, en italien.

export const IT: Omit<LandingCopy, "features"> & { features: Feature[] } = {
  defaultTagline:
    "Un programma progettato dal tuo coach, secondo il suo metodo, adattato alla tua palestra e ai tuoi vincoli, e seguito ogni giorno. Assistito da un motore di IA specializzato nella trasformazione fisica.",
  login: "Accedi",
  seePrograms: "Vedi i programmi",
  howItWorks: "Come funziona",
  heroChip: "Coaching personalizzato",
  heroChecks: ["Programma firmato dal tuo coach", "Salute e allergie prese in conto", "Seguito ogni giorno"],
  stats: [
    { v: "Il tuo coach", l: "progetta il suo metodo" },
    { v: "100 %", l: "adattato alla tua palestra e alla tua salute" },
    { v: "Motore IA", l: "al servizio del suo metodo" },
    { v: "Su misura", l: "a consumo o in abbonamento" },
  ],
  featuresChip: "Funzionalità",
  featuresTitle: "Tutto quello che serve per arrivarci",
  features: [
    { title: "Il metodo del tuo coach", body: "Il tuo programma si costruisce sul metodo del tuo coach: esercizi, serie, carichi e progressioni, pensati da lui." },
    { title: "Analisi della tua palestra", body: "Fotografa le tue macchine: il piano usa solo il materiale davvero disponibile." },
    { title: "100 % personalizzato", body: "Patologie, allergie, dieta, ambito religioso: ogni vincolo viene preso in conto." },
    { title: "Un motore, non un pilota", body: "Il tuo coach mantiene il controllo di ogni decisione. Il motore di IA gli serve per applicare il suo metodo al tuo caso senza lasciarsi sfuggire nulla." },
    { title: "Zone cardiache precise", body: "Le tue zone di intensità calcolate per tirare fuori il meglio da ogni seduta di cardio." },
    { title: "Spazio cliente completo", body: "Sedute interattive, calendario, diario alimentare tramite scansione del codice a barre, curva del peso: tutto il tuo monitoraggio nello stesso posto." },
    { title: "Strumenti di allenamento", body: "Timer di recupero integrato, diario serie per serie (kg × rip), progressione e caselle da spuntare." },
    { title: "Un assistente formato dal tuo coach", body: "Un assistente disponibile in continuo, allenato sul metodo del tuo coach. Risponde, motiva e ti accompagna ogni giorno." },
  ],
  gymChip: "La tua palestra, il tuo materiale",
  gymTitle: "La tua palestra analizzata. Il tuo programma adattato.",
  gymBody: "Fotografa la tua palestra: l'IA identifica il materiale disponibile e si assicura che ogni esercizio del tuo programma sia fattibile con quello che hai.",
  gymBullets: ["Manubri, bilancieri, cavi, macchine guidate", "Home gym con materiale limitato", "Palestra condominiale o hotel", "Allenamento solo a corpo libero"],
  gymScanLabel: "IA in analisi, materiale rilevato",
  spaceChip: "Spazio cliente",
  spaceTitle: "Il tuo programma, vivo ogni giorno.",
  spaceBody: "Più di un documento, il tuo programma è interattivo. Spunta i tuoi esercizi, lancia il tuo crono, consulta la tua nutrizione e parla con il tuo coach IA.",
  spaceBullets: ["Sedute interattive", "Checklist degli esercizi", "Crono e timer", "Nutrizione del giorno", "Monitoraggio dei progressi", "Assistente IA con un tocco"],
  nutritionChip: "Nutrizione",
  nutritionTitle: "Una nutrizione precisa quanto il tuo allenamento.",
  nutritionBody: "Calorie, macro, timing dei pasti e ricette adattate. Le tue allergie, le tue intolleranze e il tuo ambito religioso (halal, kasher, vegetariano…) presi in conto. E per sapere a che punto sei: scansioni il codice a barre di quello che mangi, calorie e macro si compilano da soli, di fronte al tuo obiettivo del giorno.",
  nutritionBullets: ["Scansione del codice a barre", "Diario del giorno di fronte al tuo obiettivo", "Halal / kasher", "Vegetariano / vegano", "Allergie e intolleranze", "Ricette a settimana"],
  stepsTitle: "3 passi verso la tua trasformazione",
  steps: [
    { k: "01", title: "Rispondi al questionario", body: "Obiettivi, livello, disponibilità, salute, allergie e preferenze alimentari." },
    { k: "02", title: "Fotografa la tua palestra", body: "Il sistema legge il materiale disponibile per adattare ogni esercizio a quello che hai." },
    { k: "03", title: "Segui il tuo programma", body: "Il tuo piano ti aspetta nel tuo spazio cliente, seduta dopo seduta, giorno dopo giorno." },
  ],
  forWhoTitle: "È fatto per te?",
  forWho: [
    { title: "Dal principiante all'avanzato", body: "Principiante, installiamo la tecnica e l'abitudine; avanzato, andiamo a cercare il sovraccarico e la performance. Il programma si regola sul tuo livello." },
    { title: "Un vincolo di salute", body: "Filtro salute all'inizio, esercizi adattati, convalida medica se serve." },
    { title: "Allergie, vegetariano, halal, kasher", body: "I tuoi vincoli alimentari rispettati in tutta la nutrizione." },
    { title: "Poco tempo", body: "Scegli i tuoi giorni; le sedute sono calibrate sulla tua realtà." },
    { title: "Palestra o casa", body: "Usiamo solo il tuo materiale, ovunque tu ti alleni." },
    { title: "Ritorno dopo una pausa", body: "Il ciclo di adattamento ti rimette in moto senza bruciarti." },
  ],
  aboutChip: "Su di me",
  authorChip: "Chi progetta il tuo programma",
  authorTitle: "Il tuo coach scrive il tuo programma. Non un robot.",
  authorBody:
    "Gli esercizi, l'ordine delle sedute, i carichi di partenza, la velocità di progressione: tutto viene dal metodo del tuo coach, da quello che ha imparato sul campo con i suoi clienti. Niente esce da un catalogo generico.",
  authorPoints: [
    { title: "Il suo metodo, per iscritto", body: "Il tuo coach ha messo nero su bianco il suo modo di lavorare: i suoi principi, i suoi esercizi preferiti, le sue progressioni, quello che si rifiuta di far fare. Il tuo programma si allinea a questo." },
    { title: "Le sue decisioni, non delle medie", body: "Due persone con lo stesso obiettivo non ricevono lo stesso piano. È il giudizio del tuo coach sul tuo caso che decide." },
    { title: "Resta raggiungibile", body: "Un programma non è un PDF che ti mandano e poi dimenticano. Il tuo coach segue quello che fai e aggiusta." },
  ],
  authorSignature: (name) => `Programmi firmati ${name}`,
  engineChip: "Il motore dietro",
  engineTitle: "Un motore specializzato nella trasformazione fisica.",
  engineBody:
    "Per applicare il suo metodo al tuo caso concreto, il tuo coach si appoggia a un motore di IA allenato per una cosa sola: costruire piani di allenamento e di nutrizione. Non è un assistente generico a cui si chiede il meteo.",
  enginePoints: [
    { title: "Quello che richiedeva ore richiede minuti", body: "Incrociare il tuo obiettivo, il tuo livello, i tuoi giorni disponibili, il tuo materiale, i tuoi vincoli di salute e i tuoi divieti alimentari: il motore fa questo lavoro di assemblaggio perché il tuo coach passi il suo tempo sulle decisioni, non sull'impaginazione." },
    { title: "Niente si perde per strada", body: "Un'allergia dichiarata nel questionario si ritrova in ogni ricetta delle dodici settimane. Una spalla dolorante mette da parte gli esercizi interessati in tutto il piano, non solo la prima settimana." },
    { title: "Il tuo piano continua a imparare", body: "I carichi che annoti, le sedute che salti, il tuo peso che cambia: il blocco successivo si ricostruisce su quello che hai davvero fatto, non su quello che era previsto." },
    { title: "Un interlocutore a qualsiasi ora", body: "Il coach IA riprende il metodo del tuo coach per rispondere alle 23 di una domenica, quando una macchina è occupata o un pasto non va bene. Il tuo coach non deve restare sveglio per questo." },
  ],
  engineLimit:
    "Il motore non decide al posto del tuo coach: applica il suo metodo. E non sostituisce né un parere medico, né lo sguardo di un professionista sulla tua tecnica.",
  navMethod: "Il metodo",
  navPrograms: "Programmi",
  navFaq: "Domande",
  leadPoints: [
    "Una settimana completa, giorno per giorno",
    "Carichi obiettivo e indicazioni tecniche",
    "Nutrizione in cifre e lista della spesa",
    "Tabella di monitoraggio da stampare",
  ],
  leadReassure: "Senza impegno, senza carta di credito",
  testimonialsTitle: "Quello che dicono i suoi clienti",
  leadChip: "Gratis",
  leadTitle: "La tua prima settimana, gratis",
  heroLead: "La mia prima settimana, gratis",
  leadBody: "Un piano vero da seguire, calibrato sul tuo obiettivo, sul tuo livello e sul tuo materiale. Pronto da stampare.",
  leadCta: "Ricevere il mio programma",
  programsChip: "Programmi",
  programsTitle: "Scegli il tuo programma",
  noOffer: "Nessuna offerta disponibile al momento. Torna presto.",
  giftTitle: "Voglia di fare un regalo?",
  giftBody: "Regala un programma a qualcuno: paghi tu, la persona riceve un codice da usare liberamente.",
  giftCta: "Voglio regalare un programma",
  faqChip: "FAQ",
  faqTitle: "Domande frequenti",
  faqs: [
    { q: "Serve una palestra o materiale particolare?", a: "No. Fotografi quello che hai, palestra completa, home gym o due manubri, e il programma si costruisce unicamente con quel materiale." },
    { q: "Sono principiante, va bene per me?", a: "Sì. L'inizio del programma è dedicato alla tecnica e a installare l'abitudine. Poi si progredisce gradualmente." },
    { q: "Come funziona il pagamento?", a: "Il pagamento è sicuro tramite Stripe, direttamente con il tuo coach. A seconda del programma scelto, è un pagamento unico o un abbonamento (mensile o annuale), annullabile in qualsiasi momento dal tuo spazio." },
    { q: "Chi progetta davvero il programma?", a: "Il tuo coach. Il programma si costruisce sul SUO metodo; si appoggia a un'IA che ha allenato sul suo modo di lavorare. L'assistente IA prolunga questo accompagnamento ogni giorno, ma non sostituisce il tuo coach né un parere medico." },
    { q: "Ho un infortunio, una patologia o una gravidanza?", a: "Un filtro salute all'inizio rileva le situazioni a rischio. Il programma si adatta o si mette in pausa in attesa del parere del tuo medico." },
    { q: "3 mesi o 12 mesi, qual è la differenza?", a: "Quello da 3 mesi è uno sprint con un traguardo: 3 cicli che salgono di intensità, per un risultato visibile in 12 settimane. Quello da 12 mesi è un programma che impara da te: 4 blocchi da 3 mesi, ciascuno ricostruito su quello che hai davvero fatto nel precedente, con un orientamento che cambia nel corso dell'anno (basi, volume, forza, picco)." },
    { q: "Che cosa succede dopo il programma?", a: "Il coach IA si disattiva alla fine, ma il tuo piano resta consultabile ancora per un po' in sola lettura. Su un 3 mesi, il tuo coach ti propone di continuare con un 12 mesi scalando quello che hai già pagato." },
  ],
  finalTitle: "La tua trasformazione comincia oggi.",
  legalNote: "Accompagnamento sportivo e di benessere, senza finalità terapeutiche. L'accompagnamento nutrizionale è un aiuto nella scelta dei pasti, non una prescrizione dietetica. Non sostituisce un parere medico.",
  footerLogin: "Accedi",
  footerLegal: "Note legali",
  footerPrivacy: "Privacy",
  footerTerms: "Condizioni",
  poweredBy: "Con la tecnologia di",
  mostChosen: "Il più scelto",
  oneTime: "pagamento unico",
  perMonthOn: (amount, months) => `ossia ${amount}/mese per ${months} mesi`,
  choose: "Scegliere questo programma",
  soon: "Presto disponibile",
  payOnce: "In una volta",
  payInstallments: (n) => `In ${n} rate`,
  perMonthTimes: (n) => `/mese × ${n}`,
  autoStop: (n) => `${n} pagamenti, e poi più nulla: lo stop è automatico.`,
  totalOver: (amount, n) => `ossia ${amount} in totale su ${n} mesi`,
  mockCoach: "Coach IA",
  mockCoachSub: "risponde in diretta",
  mockSession: "Seduta del giorno",
  mockDay: "Giorno 24",
};

export const GYM_IT: Overrides = {
  testimonialsTitle: "Quello che dicono i suoi iscritti",
  defaultTagline:
    "Un programma costruito dal team della tua palestra, con le macchine che stanno qui, e che ti segue anche nei giorni in cui non vieni. Assistito da un motore specializzato nella trasformazione fisica.",
  heroChip: "Programma incluso nel tuo abbonamento",
  heroChecks: ["Costruito sul materiale della palestra", "Seguito dal team", "Anche nei giorni senza venire"],
  stats: [
    { v: "Il nostro team", l: "progetta il tuo programma" },
    { v: "Le nostre macchine", l: "quelle che hai a portata di mano" },
    { v: "7 g / 7", l: "un piano anche fuori dalla palestra" },
    { v: "Senza costi extra", l: "incluso nel tuo abbonamento" },
  ],
  featuresTitle: "Quello che il tuo abbonamento ti dà in più",
  features: [
    { title: "Il metodo della palestra", body: "I nostri coach hanno messo nero su bianco il loro modo di far progredire: è quello che costruisce il tuo piano, non un modello generico comprato altrove." },
    { title: "Le nostre macchine, non quelle di un catalogo", body: "Il parco della palestra è conosciuto postazione per postazione. Il tuo programma non ti manda mai su un attrezzo che non abbiamo, né su quello sempre occupato alle 18." },
    { title: "Adattato a te, non al gruppo", body: "Patologie, allergie, dieta, ambito religioso, orari: il tuo piano tiene conto della tua situazione, non della media degli iscritti." },
    { title: "Un motore, non un pilota", body: "Il team mantiene il controllo di ogni decisione. Il motore di IA gli serve per applicare il suo metodo a ogni iscritto senza lasciarsi sfuggire nulla." },
    { title: "Zone cardiache precise", body: "Le tue zone di intensità calcolate, perché il cardio della palestra serva davvero a qualcosa." },
    { title: "Il tuo spazio iscritto", body: "Sedute interattive, calendario, diario dei carichi, diario alimentare tramite scansione del codice a barre, curva del peso: quello che fai qui e altrove, nello stesso posto." },
    { title: "Strumenti di allenamento", body: "Timer di recupero, diario serie per serie, progressione visibile: di che allenarsi da soli senza perdere il filo." },
    { title: "Un interlocutore fuori dagli orari di apertura", body: "Il coach IA riprende il metodo della palestra e risponde quando la reception è chiusa, in viaggio o in vacanza." },
  ],
  gymChip: "Il nostro parco",
  gymTitle: "Le nostre macchine sono già nel tuo programma.",
  gymBody:
    "Sappiamo esattamente cosa contiene la palestra. Il tuo piano è scritto con quel materiale, e se ti alleni altrove per una settimana, fotografi il posto e il programma si adatta.",
  gymBullets: ["La zona pesi liberi", "Le macchine guidate", "Lo spazio cardio", "E la tua palestra in vacanza, in foto"],
  spaceChip: "Spazio iscritto",
  spaceTitle: "Il tuo programma ti segue fuori dalla palestra.",
  spaceBody:
    "La maggior parte degli abbandoni arriva nelle settimane in cui non si viene. Il tuo spazio iscritto ti dice cosa fare quel giorno, in palestra o altrove, e tiene traccia di quello che hai fatto.",
  authorChip: "Chi progetta il tuo programma",
  authorTitle: "I coach della palestra. Non un robot.",
  authorBody:
    "Gli esercizi, l'ordine delle sedute, i carichi di partenza, la velocità di progressione: tutto viene dal metodo del nostro team, da quello che vede funzionare qui, in questa sala, con i nostri iscritti.",
  authorPoints: [
    { title: "Un metodo della casa", body: "I nostri coach hanno scritto il loro modo di lavorare: i loro principi, i loro esercizi di riferimento, le loro progressioni, quello che si rifiutano di far fare. Il tuo programma si allinea a questo." },
    { title: "Persone che puoi incrociare", body: "Non sono programmi comprati da un fornitore lontano. Il team che li firma è quello che vedi in sala." },
    { title: "Un passaggio di testimone tra due visite", body: "Quello che un coach ti ha corretto in seduta si ritrova nel tuo piano della settimana, invece di andare perso." },
  ],
  authorSignature: (name) => `Programmi firmati dal team ${name}`,
  engineBody:
    "Per applicare il suo metodo a ogni iscritto, il team si appoggia a un motore di IA allenato per una cosa sola: costruire piani di allenamento e di nutrizione. Non è un assistente generico a cui si chiede il meteo.",
  enginePoints: [
    { title: "Un piano su misura per ogni iscritto", body: "Scrivere a mano un programma personalizzato per ogni iscritto sarebbe impossibile alla scala di una palestra. Il motore lo rende fattibile senza cadere nel programma fotocopiato." },
    { title: "Niente si perde per strada", body: "Un'allergia dichiarata all'iscrizione si ritrova in ogni ricetta delle dodici settimane. Una spalla dolorante mette da parte gli esercizi interessati in tutto il piano." },
    { title: "Il tuo piano continua a imparare", body: "I carichi che annoti, le sedute che salti, il tuo peso che cambia: il blocco successivo si ricostruisce su quello che hai davvero fatto." },
    { title: "Disponibile quando la palestra è chiusa", body: "Il coach IA riprende il metodo del team per rispondere alle 23 di una domenica, quando una macchina è occupata o un pasto non va bene." },
  ],
  engineLimit:
    "Il motore non decide al posto dei nostri coach: applica il loro metodo. E non sostituisce né un parere medico, né lo sguardo di un coach sulla tua tecnica.",
  stepsTitle: "3 passi, già da oggi",
  steps: [
    { k: "01", title: "Rispondi al questionario", body: "Obiettivi, livello, disponibilità, salute, allergie e preferenze alimentari. Dieci minuti, una volta sola." },
    { k: "02", title: "Il tuo piano si costruisce sul nostro parco", body: "Il materiale della palestra è già conosciuto. Fotografi solo se ti alleni altrove." },
    { k: "03", title: "Allenati, qui e altrove", body: "Il tuo spazio iscritto ti dice cosa fare ogni giorno, e annota quello che fai." },
  ],
  forWhoTitle: "Per quale iscritto?",
  forWho: [
    { title: "Quello che gira a vuoto", body: "Vieni regolarmente ma rifai le stesse macchine da mesi. Ti diamo una progressione scritta." },
    { title: "Quello che è appena arrivato", body: "Non sai da dove cominciare in sala. Il piano ti dice cosa fare, in che ordine, con che carico." },
    { title: "Quello che molla d'inverno", body: "Le settimane in cui non vieni non sono più settimane perse: il piano ti segue a casa." },
    { title: "Quello che ha un vincolo di salute", body: "Filtro salute all'inizio, esercizi adattati, convalida medica se serve." },
    { title: "Quello che viaggia", body: "Una foto della palestra dell'hotel basta ad adattare la settimana." },
    { title: "Quello che vuole la nutrizione", body: "Non solo l'allenamento: calorie, macro e ricette che tengono conto dei tuoi vincoli." },
  ],
  leadTitle: "Prenditi una settimana gratis",
  heroLead: "Una settimana gratis, per iniziare",
  leadBody: "Un piano vero da seguire, calibrato sul tuo obiettivo e sul materiale che hai. Pronto da stampare.",
  programsTitle: "Le nostre formule",
  finalTitle: "La tua palestra. Il tuo programma. Dalla prossima seduta.",
  giftTitle: "Voglia di fare un regalo?",
  giftBody: "Regala un accompagnamento a qualcuno: paghi tu, la persona riceve un codice da usare liberamente.",
};
