import type { Feature, LandingCopy, Overrides } from "./coach-copy";

// Textes de vente des landings pro->client, en néerlandais.

export const NL: Omit<LandingCopy, "features"> & { features: Feature[] } = {
  defaultTagline:
    "Een programma opgesteld door je coach, volgens zijn methode, afgestemd op jouw sportschool en jouw beperkingen, en dagelijks gevolgd. Ondersteund door een AI-motor gespecialiseerd in fysieke transformatie.",
  login: "Inloggen",
  seePrograms: "Bekijk de programma's",
  howItWorks: "Hoe het werkt",
  heroChip: "Persoonlijke coaching",
  heroChecks: ["Programma ondertekend door je coach", "Gezondheid en allergieën meegenomen", "Dagelijks gevolgd"],
  stats: [
    { v: "Je coach", l: "ontwerpt zijn methode" },
    { v: "100 %", l: "afgestemd op jouw sportschool en jouw gezondheid" },
    { v: "AI-motor", l: "in dienst van zijn methode" },
    { v: "Op maat", l: "per stuk of via abonnement" },
  ],
  featuresChip: "Functies",
  featuresTitle: "Alles wat je nodig hebt om er te komen",
  features: [
    { title: "De methode van je coach", body: "Je programma wordt gebouwd op de methode van je coach: oefeningen, sets, gewichten en progressies, door hem bedacht." },
    { title: "Analyse van je sportschool", body: "Fotografeer je machines: het plan gebruikt alleen materiaal dat er echt is." },
    { title: "100 % persoonlijk", body: "Aandoeningen, allergieën, dieet, religieus kader: met elke beperking wordt rekening gehouden." },
    { title: "Een motor, geen piloot", body: "Je coach houdt elke beslissing in eigen hand. De AI-motor helpt hem zijn methode op jouw geval toe te passen zonder iets te missen." },
    { title: "Precieze hartslagzones", body: "Je intensiteitszones berekend om het beste uit elke cardiotraining te halen." },
    { title: "Volledige klantomgeving", body: "Interactieve trainingen, kalender, voedingsdagboek via streepjescode, gewichtscurve: al je opvolging op één plek." },
    { title: "Trainingsgereedschap", body: "Ingebouwde rusttimer, logboek set voor set (kg × herh.), progressie en vinkjes." },
    { title: "Een assistent opgeleid door je coach", body: "Een assistent die er altijd is, getraind op de methode van je coach. Hij antwoordt, motiveert en begeleidt je elke dag." },
  ],
  gymChip: "Jouw sportschool, jouw materiaal",
  gymTitle: "Jouw sportschool geanalyseerd. Jouw programma aangepast.",
  gymBody: "Fotografeer je sportschool: de AI herkent het beschikbare materiaal en zorgt dat elke oefening in je programma haalbaar is met wat je hebt.",
  gymBullets: ["Dumbbells, stangen, kabels, geleide machines", "Home gym met beperkt materiaal", "Sportzaal in het complex of het hotel", "Trainen met alleen lichaamsgewicht"],
  gymScanLabel: "AI analyseert, materiaal herkend",
  spaceChip: "Klantomgeving",
  spaceTitle: "Je programma, elke dag levend.",
  spaceBody: "Meer dan een document: je programma is interactief. Vink je oefeningen af, start je klok, bekijk je voeding en praat met je AI-coach.",
  spaceBullets: ["Interactieve trainingen", "Checklist van oefeningen", "Klok en timer", "Voeding van vandaag", "Voortgang volgen", "AI-assistent met één tik"],
  nutritionChip: "Voeding",
  nutritionTitle: "Voeding net zo precies als je training.",
  nutritionBody: "Calorieën, macro's, timing van de maaltijden en aangepaste recepten. Je allergieën, je intoleranties en je religieuze kader (halal, koosjer, vegetarisch…) meegenomen. En om te weten waar je staat: je scant de streepjescode van wat je eet, de calorieën en de macro's vullen zichzelf in, naast je doel van die dag.",
  nutritionBullets: ["Streepjescode scannen", "Dagboek naast je doel", "Halal / koosjer", "Vegetarisch / veganistisch", "Allergieën en intoleranties", "Recepten per week"],
  stepsTitle: "3 stappen naar je transformatie",
  steps: [
    { k: "01", title: "Vul de vragenlijst in", body: "Doelen, niveau, beschikbaarheid, gezondheid, allergieën en voedingsvoorkeuren." },
    { k: "02", title: "Fotografeer je sportschool", body: "Het systeem leest het beschikbare materiaal om elke oefening af te stemmen op wat je hebt." },
    { k: "03", title: "Volg je programma", body: "Je plan wacht op je in je klantomgeving, training na training, dag na dag." },
  ],
  forWhoTitle: "Is dit iets voor jou?",
  forWho: [
    { title: "Van beginner tot gevorderd", body: "Als beginner bouwen we techniek en gewoonte op; als gevorderde gaan we voor overbelasting en prestatie. Het programma stelt zich af op jouw niveau." },
    { title: "Een gezondheidsbeperking", body: "Gezondheidsfilter aan het begin, aangepaste oefeningen, medische goedkeuring waar nodig." },
    { title: "Allergieën, vegetarisch, halal, koosjer", body: "Je voedingsbeperkingen worden in de hele voeding gerespecteerd." },
    { title: "Weinig tijd", body: "Jij kiest je dagen; de trainingen zijn afgestemd op jouw werkelijkheid." },
    { title: "Sportschool of thuis", body: "We gebruiken alleen jouw materiaal, waar je ook traint." },
    { title: "Terug na een pauze", body: "De aanpassingscyclus brengt je weer op gang zonder je op te branden." },
  ],
  aboutChip: "Over mij",
  authorChip: "Wie je programma opstelt",
  authorTitle: "Je coach schrijft je programma. Geen robot.",
  authorBody:
    "De oefeningen, de volgorde van de trainingen, de startgewichten, de snelheid van de progressie: alles komt uit de methode van je coach, uit wat hij in de praktijk met zijn klanten geleerd heeft. Niets komt uit een algemene catalogus.",
  authorPoints: [
    { title: "Zijn methode, op papier", body: "Je coach heeft vastgelegd hoe hij werkt: zijn principes, zijn favoriete oefeningen, zijn progressies, wat hij weigert te laten doen. Je programma sluit daarop aan." },
    { title: "Zijn keuzes, geen gemiddelden", body: "Twee mensen met hetzelfde doel krijgen niet hetzelfde plan. Het oordeel van je coach over jouw geval beslist." },
    { title: "Hij blijft bereikbaar", body: "Een programma is geen pdf die ze je sturen en vergeten. Je coach volgt wat je doet en stelt bij." },
  ],
  authorSignature: (name) => `Programma's ondertekend door ${name}`,
  engineChip: "De motor erachter",
  engineTitle: "Een motor gespecialiseerd in fysieke transformatie.",
  engineBody:
    "Om zijn methode op jouw concrete geval toe te passen leunt je coach op een AI-motor die voor één ding getraind is: trainings- en voedingsplannen bouwen. Het is geen algemene assistent aan wie je het weer vraagt.",
  enginePoints: [
    { title: "Wat uren kostte, kost minuten", body: "Je doel, je niveau, je beschikbare dagen, je materiaal, je gezondheidsbeperkingen en je voedingsverboden combineren: die montage doet de motor, zodat je coach zijn tijd aan de beslissingen besteedt en niet aan de opmaak." },
    { title: "Onderweg gaat er niets verloren", body: "Een allergie die je in de vragenlijst opgeeft, komt terug in elk recept van de twaalf weken. Een gevoelige schouder haalt de betrokken oefeningen uit het hele plan, niet alleen uit de eerste week." },
    { title: "Je plan blijft leren", body: "De gewichten die je noteert, de trainingen die je overslaat, je gewicht dat verandert: het volgende blok wordt gebouwd op wat je echt gedaan hebt, niet op wat er gepland stond." },
    { title: "Een aanspreekpunt op elk moment", body: "De AI-coach neemt de methode van je coach over om op zondag om 23 uur te antwoorden, als een machine bezet is of een maaltijd niet uitkomt. Je coach hoeft daar niet voor wakker te blijven." },
  ],
  engineLimit:
    "De motor beslist niet in plaats van je coach: hij past zijn methode toe. En hij vervangt geen medisch advies, en ook niet de blik van een vakman op je techniek.",
  navMethod: "De methode",
  navPrograms: "Programma's",
  navFaq: "Vragen",
  leadPoints: [
    "Een volledige week, dag voor dag",
    "Doelgewichten en technische aanwijzingen",
    "Voeding in cijfers en boodschappenlijst",
    "Opvolgtabel om af te drukken",
  ],
  leadReassure: "Zonder verplichting, zonder bankkaart",
  testimonialsTitle: "Wat zijn klanten zeggen",
  leadChip: "Gratis",
  leadTitle: "Je eerste week, gratis",
  heroLead: "Mijn eerste week, gratis",
  leadBody: "Een echt plan om te volgen, afgestemd op je doel, je niveau en je materiaal. Klaar om af te drukken.",
  leadCta: "Mijn programma ontvangen",
  programsChip: "Programma's",
  programsTitle: "Kies je programma",
  noOffer: "Op dit moment is er geen aanbod. Kom snel terug.",
  giftTitle: "Zin om iets cadeau te doen?",
  giftBody: "Geef iemand een programma cadeau: jij betaalt, die persoon krijgt een code om vrij te gebruiken.",
  giftCta: "Ik wil een programma cadeau doen",
  faqChip: "FAQ",
  faqTitle: "Veelgestelde vragen",
  faqs: [
    { q: "Heb ik een sportschool of speciaal materiaal nodig?", a: "Nee. Je fotografeert wat je hebt, een volledige sportschool, een home gym of een paar dumbbells, en het programma wordt uitsluitend met dat materiaal gebouwd." },
    { q: "Ik ben beginner, is dit geschikt?", a: "Ja. Het begin van het programma draait om techniek en om de gewoonte opbouwen. Daarna gaat het stap voor stap omhoog." },
    { q: "Hoe werkt de betaling?", a: "Betalen gaat veilig via Stripe, rechtstreeks bij je coach. Afhankelijk van het gekozen programma is het een eenmalige betaling of een abonnement (maandelijks of jaarlijks), dat je altijd vanuit je omgeving kunt opzeggen." },
    { q: "Wie stelt het programma echt op?", a: "Je coach. Het programma wordt gebouwd op ZIJN methode; hij leunt op een AI die hij op zijn manier van werken getraind heeft. De AI-assistent verlengt die begeleiding in het dagelijks leven, maar vervangt niet je coach en ook geen medisch advies." },
    { q: "Ik heb een blessure, een aandoening of ik ben zwanger?", a: "Een gezondheidsfilter aan het begin herkent risicosituaties. Het programma past zich aan of gaat op pauze tot je arts advies heeft gegeven." },
    { q: "3 maanden of 12 maanden, wat is het verschil?", a: "De 3 maanden is een sprint met een finishlijn: 3 cycli die in intensiteit oplopen, voor een zichtbaar resultaat in 12 weken. De 12 maanden is een programma dat van je leert: 4 blokken van 3 maanden, elk opgebouwd op wat je in het vorige echt gedaan hebt, met een richting die in de loop van het jaar verandert (basis, volume, kracht, piek)." },
    { q: "Wat gebeurt er na het programma?", a: "De AI-coach gaat aan het eind uit, maar je plan blijft daarna nog een tijd te bekijken in alleen-lezen. Bij een 3 maanden stelt je coach je voor door te gaan met 12 maanden, waarbij wat je al betaald hebt eraf gaat." },
  ],
  finalTitle: "Je transformatie begint vandaag.",
  legalNote: "Sport- en welzijnsbegeleiding, zonder therapeutisch doel. De voedingsbegeleiding is een hulp bij het kiezen van je maaltijden, geen dieetvoorschrift. Ze vervangt geen medisch advies.",
  footerLogin: "Inloggen",
  footerLegal: "Juridische informatie",
  footerPrivacy: "Privacy",
  footerTerms: "Voorwaarden",
  poweredBy: "Mogelijk gemaakt door",
  mostChosen: "Het meest gekozen",
  oneTime: "eenmalige betaling",
  perMonthOn: (amount, months) => `dat is ${amount}/maand over ${months} maanden`,
  choose: "Dit programma kiezen",
  soon: "Binnenkort beschikbaar",
  payOnce: "In 1 keer",
  payInstallments: (n) => `In ${n} termijnen`,
  perMonthTimes: (n) => `/maand × ${n}`,
  autoStop: (n) => `${n} betalingen, en daarna niets meer: het stopt vanzelf.`,
  totalOver: (amount, n) => `dat is ${amount} in totaal over ${n} maanden`,
  mockCoach: "AI-coach",
  mockCoachSub: "antwoordt live",
  mockSession: "Training van vandaag",
  mockDay: "Dag 24",
};

export const GYM_NL: Overrides = {
  testimonialsTitle: "Wat zijn leden zeggen",
  defaultTagline:
    "Een programma gebouwd door het team van jouw sportschool, met de machines die hier staan, en dat je ook volgt op de dagen dat je niet komt. Ondersteund door een motor gespecialiseerd in fysieke transformatie.",
  heroChip: "Programma inbegrepen bij je abonnement",
  heroChecks: ["Gebouwd op het materiaal van de sportschool", "Gevolgd door het team", "Ook op de dagen zonder bezoek"],
  stats: [
    { v: "Ons team", l: "stelt je programma op" },
    { v: "Onze machines", l: "die je hier bij de hand hebt" },
    { v: "7 op 7", l: "een plan ook buiten de sportschool" },
    { v: "Zonder meerprijs", l: "inbegrepen bij je abonnement" },
  ],
  featuresTitle: "Wat je abonnement je extra oplevert",
  features: [
    { title: "De methode van de sportschool", body: "Onze coaches hebben vastgelegd hoe zij mensen laten groeien: dat bouwt jouw plan, geen algemeen sjabloon dat elders gekocht is." },
    { title: "Onze machines, niet die uit een catalogus", body: "Het park van de sportschool is per toestel bekend. Je programma stuurt je nooit naar een apparaat dat we niet hebben, en ook niet naar het toestel dat om 18 uur altijd bezet is." },
    { title: "Afgestemd op jou, niet op de groep", body: "Aandoeningen, allergieën, dieet, religieus kader, werktijden: je plan houdt rekening met jouw situatie, niet met het gemiddelde van de leden." },
    { title: "Een motor, geen piloot", body: "Het team houdt elke beslissing in eigen hand. De AI-motor helpt hen hun methode op elk lid toe te passen zonder iets te missen." },
    { title: "Precieze hartslagzones", body: "Je intensiteitszones berekend, zodat de cardio in de zaal echt ergens toe dient." },
    { title: "Jouw ledenomgeving", body: "Interactieve trainingen, kalender, gewichtenlogboek, voedingsdagboek via streepjescode, gewichtscurve: wat je hier en elders doet, op één plek." },
    { title: "Trainingsgereedschap", body: "Rusttimer, logboek set voor set, zichtbare progressie: genoeg om alleen te trainen zonder de draad kwijt te raken." },
    { title: "Een aanspreekpunt buiten de openingstijden", body: "De AI-coach neemt de methode van de sportschool over en antwoordt als de balie dicht is, op reis of in de vakantie." },
  ],
  gymChip: "Ons park",
  gymTitle: "Onze machines staan al in je programma.",
  gymBody:
    "We weten precies wat de sportschool heeft. Je plan is met dat materiaal geschreven, en als je een week ergens anders traint, fotografeer je die plek en past het programma zich aan.",
  gymBullets: ["De vrije-gewichtenzone", "De geleide machines", "De cardioruimte", "En je vakantiesportschool, op de foto"],
  spaceChip: "Ledenomgeving",
  spaceTitle: "Je programma volgt je ook buiten de sportschool.",
  spaceBody:
    "De meeste mensen haken af in de weken dat ze niet komen. Je ledenomgeving zegt je wat je die dag doet, in de zaal of ergens anders, en houdt bij wat je gedaan hebt.",
  authorChip: "Wie je programma opstelt",
  authorTitle: "De coaches van de sportschool. Geen robot.",
  authorBody:
    "De oefeningen, de volgorde van de trainingen, de startgewichten, de snelheid van de progressie: alles komt uit de methode van ons team, uit wat het hier ziet werken, in deze zaal, bij onze leden.",
  authorPoints: [
    { title: "Een eigen methode", body: "Onze coaches hebben hun manier van werken opgeschreven: hun principes, hun vaste oefeningen, hun progressies, wat ze weigeren te laten doen. Je programma sluit daarop aan." },
    { title: "Mensen die je hier tegenkomt", body: "Het zijn geen programma's gekocht bij een verre leverancier. Het team dat ze ondertekent is het team dat je in de zaal ziet." },
    { title: "Een estafette tussen twee bezoeken", body: "Wat een coach tijdens de training bij je heeft bijgestuurd, staat in je plan van die week, in plaats van verloren te gaan." },
  ],
  authorSignature: (name) => `Programma's ondertekend door het team van ${name}`,
  engineBody:
    "Om hun methode op elk lid toe te passen leunt het team op een AI-motor die voor één ding getraind is: trainings- en voedingsplannen bouwen. Het is geen algemene assistent aan wie je het weer vraagt.",
  enginePoints: [
    { title: "Een plan op maat voor elk lid", body: "Voor elk lid met de hand een persoonlijk programma schrijven zou op de schaal van een sportschool onmogelijk zijn. De motor maakt het haalbaar zonder in het gekopieerde programma te vervallen." },
    { title: "Onderweg gaat er niets verloren", body: "Een allergie die bij de inschrijving is opgegeven, komt terug in elk recept van de twaalf weken. Een gevoelige schouder haalt de betrokken oefeningen uit het hele plan." },
    { title: "Je plan blijft leren", body: "De gewichten die je noteert, de trainingen die je overslaat, je gewicht dat verandert: het volgende blok wordt gebouwd op wat je echt gedaan hebt." },
    { title: "Beschikbaar als de sportschool dicht is", body: "De AI-coach neemt de methode van het team over om op zondag om 23 uur te antwoorden, als een machine bezet is of een maaltijd niet uitkomt." },
  ],
  engineLimit:
    "De motor beslist niet in plaats van onze coaches: hij past hun methode toe. En hij vervangt geen medisch advies, en ook niet de blik van een coach op je techniek.",
  stepsTitle: "3 stappen, vanaf vandaag",
  steps: [
    { k: "01", title: "Vul de vragenlijst in", body: "Doelen, niveau, beschikbaarheid, gezondheid, allergieën en voedingsvoorkeuren. Tien minuten, één keer." },
    { k: "02", title: "Je plan wordt op ons park gebouwd", body: "Het materiaal van de sportschool is al bekend. Je fotografeert alleen als je ergens anders traint." },
    { k: "03", title: "Train, hier en elders", body: "Je ledenomgeving zegt je elke dag wat je doet, en noteert wat je gedaan hebt." },
  ],
  forWhoTitle: "Voor welk lid?",
  forWho: [
    { title: "Wie in kringetjes draait", body: "Je komt regelmatig maar doet al maanden dezelfde machines. Wij geven je een uitgeschreven progressie." },
    { title: "Wie net binnen is", body: "Je weet niet waar je in de zaal moet beginnen. Het plan zegt je wat je doet, in welke volgorde, met welk gewicht." },
    { title: "Wie in de winter afhaakt", body: "De weken dat je niet komt zijn geen verloren weken meer: het plan volgt je thuis." },
    { title: "Wie een gezondheidsbeperking heeft", body: "Gezondheidsfilter aan het begin, aangepaste oefeningen, medische goedkeuring waar nodig." },
    { title: "Wie op reis is", body: "Een foto van de hotelsportschool is genoeg om de week aan te passen." },
    { title: "Wie ook voeding wil", body: "Niet alleen de training: calorieën, macro's en recepten die rekening houden met jouw beperkingen." },
  ],
  leadTitle: "Pak een gratis week",
  heroLead: "Een gratis week, om te beginnen",
  leadBody: "Een echt plan om te volgen, afgestemd op je doel en op het materiaal dat je hebt. Klaar om af te drukken.",
  programsTitle: "Onze formules",
  finalTitle: "Jouw sportschool. Jouw programma. Vanaf je volgende training.",
  giftTitle: "Zin om iets cadeau te doen?",
  giftBody: "Geef iemand begeleiding cadeau: jij betaalt, die persoon krijgt een code om vrij te gebruiken.",
};
