import type { Feature, LandingCopy, Overrides } from "./coach-copy";

// Textes de vente des landings pro->client, en espagnol.

export const ES: Omit<LandingCopy, "features"> & { features: Feature[] } = {
  defaultTagline:
    "Un programa diseñado por tu coach, según su método, adaptado a tu gimnasio y a tus restricciones, y con seguimiento diario. Asistido por un motor de IA especializado en transformación física.",
  login: "Iniciar sesión",
  seePrograms: "Ver los programas",
  howItWorks: "Cómo funciona",
  heroChip: "Coaching personalizado",
  heroChecks: ["Programa firmado por tu coach", "Salud y alergias tenidas en cuenta", "Seguimiento diario"],
  stats: [
    { v: "Tu coach", l: "diseña tu método" },
    { v: "100 %", l: "adaptado a tu gimnasio y tu salud" },
    { v: "Motor IA", l: "al servicio de su método" },
    { v: "A medida", l: "por unidad o por suscripción" },
  ],
  featuresChip: "Funcionalidades",
  featuresTitle: "Todo lo que hace falta para conseguirlo",
  features: [
    { title: "El método de tu coach", body: "Tu programa se construye sobre el método de tu coach: ejercicios, series, cargas y progresiones, pensados por él." },
    { title: "Análisis de tu gimnasio", body: "Fotografía tus máquinas: el plan solo usa el material realmente disponible." },
    { title: "100 % personalizado", body: "Patologías, alergias, dieta, marco religioso: cada restricción se tiene en cuenta." },
    { title: "Un motor, no un piloto", body: "Tu coach mantiene el control de cada decisión. El motor de IA le sirve para aplicar su método a tu caso sin dejar pasar nada." },
    { title: "Zonas cardíacas precisas", body: "Tus zonas de intensidad calculadas para sacar lo mejor de cada sesión de cardio." },
    { title: "Espacio cliente completo", body: "Sesiones interactivas, calendario, diario alimentario por escaneo de código de barras, curva de peso: todo tu seguimiento en el mismo sitio." },
    { title: "Herramientas de entrenamiento", body: "Temporizador de descanso integrado, diario serie a serie (kg × reps), progresión y casillas." },
    { title: "Un asistente formado por tu coach", body: "Un asistente disponible de forma continua, entrenado con el método de tu coach. Responde, motiva y te acompaña en el día a día." },
  ],
  gymChip: "Tu gimnasio, tu material",
  gymTitle: "Tu gimnasio analizado. Tu programa adaptado.",
  gymBody: "Fotografía tu gimnasio: la IA identifica el material disponible y se asegura de que cada ejercicio de tu programa sea realizable con lo que tienes.",
  gymBullets: ["Mancuernas, barras, poleas, máquinas guiadas", "Home gym con material limitado", "Gimnasio comunitario u hotel", "Entrenamiento solo con peso corporal"],
  gymScanLabel: "IA analizando, material detectado",
  spaceChip: "Espacio cliente",
  spaceTitle: "Tu programa, vivo en el día a día.",
  spaceBody: "Más que un documento, tu programa es interactivo. Marca tus ejercicios, lanza tu cronómetro, consulta tu nutrición y habla con tu coach IA.",
  spaceBullets: ["Sesiones interactivas", "Checklist de ejercicios", "Cronómetro y temporizador", "Nutrición del día", "Seguimiento del progreso", "Asistente IA en un toque"],
  nutritionChip: "Nutrición",
  nutritionTitle: "Una nutrición tan precisa como tu entrenamiento.",
  nutritionBody: "Calorías, macros, timing de las comidas y recetas adaptadas. Tus alergias, intolerancias y tu marco religioso (halal, kosher, vegetariano…) tenidos en cuenta. Y para saber dónde estás: escaneas el código de barras de lo que comes, las calorías y los macros se rellenan solos, frente a tu objetivo del día.",
  nutritionBullets: ["Escaneo de código de barras", "Diario del día frente a tu objetivo", "Halal / kosher", "Vegetariano / vegano", "Alergias e intolerancias", "Recetas por semana"],
  stepsTitle: "3 pasos hacia tu transformación",
  steps: [
    { k: "01", title: "Responde al cuestionario", body: "Objetivos, nivel, disponibilidad, salud, alergias y preferencias alimentarias." },
    { k: "02", title: "Fotografía tu gimnasio", body: "El sistema lee el material disponible para adaptar cada ejercicio a lo que tienes." },
    { k: "03", title: "Sigue tu programa", body: "Tu plan te espera en tu espacio cliente, sesión a sesión, día tras día." },
  ],
  forWhoTitle: "¿Es para ti?",
  forWho: [
    { title: "Del principiante al avanzado", body: "Principiante, instalamos la técnica y el hábito; avanzado, buscamos la sobrecarga y el rendimiento. El programa se ajusta a tu nivel." },
    { title: "Una restricción de salud", body: "Filtro de salud al inicio, ejercicios adaptados, validación médica si hace falta." },
    { title: "Alergias, vegetariano, halal, kosher", body: "Tus restricciones alimentarias respetadas en toda la nutrición." },
    { title: "Poco tiempo", body: "Eliges tus días; las sesiones están calibradas para tu realidad." },
    { title: "Gimnasio o casa", body: "Solo usamos tu material, entrenes donde entrenes." },
    { title: "Vuelta tras una pausa", body: "El ciclo de adaptación te pone en marcha sin quemarte." },
  ],
  aboutChip: "Sobre mí",
  authorChip: "Quién diseña tu programa",
  authorTitle: "Tu coach escribe tu programa. No un robot.",
  authorBody:
    "Los ejercicios, el orden de las sesiones, las cargas de partida, la velocidad de progresión: todo viene del método de tu coach, de lo que ha aprendido sobre el terreno con sus clientes. Nada sale de un catálogo genérico.",
  authorPoints: [
    { title: "Su método, por escrito", body: "Tu coach ha dejado constancia de su forma de trabajar: sus principios, sus ejercicios preferidos, sus progresiones, lo que se niega a hacer hacer. Tu programa se ajusta a ello." },
    { title: "Sus decisiones, no medias", body: "Dos personas con el mismo objetivo no reciben el mismo plan. Es el juicio de tu coach sobre tu caso el que decide." },
    { title: "Sigue localizable", body: "Un programa no es un PDF que te envían y olvidan. Tu coach sigue lo que haces y ajusta." },
  ],
  authorSignature: (name) => `Programas firmados por ${name}`,
  engineChip: "El motor detrás",
  engineTitle: "Un motor especializado en transformación física.",
  engineBody:
    "Para aplicar su método a tu caso concreto, tu coach se apoya en un motor de IA entrenado para una sola cosa: construir planes de entrenamiento y de nutrición. No es un asistente genérico al que se le pregunta el tiempo.",
  enginePoints: [
    { title: "Lo que llevaba horas lleva minutos", body: "Cruzar tu objetivo, tu nivel, tus días disponibles, tu material, tus restricciones de salud y tus prohibiciones alimentarias: el motor hace ese trabajo de ensamblaje para que tu coach dedique su tiempo a las decisiones, no a la maquetación." },
    { title: "Nada se olvida por el camino", body: "Una alergia declarada en el cuestionario se encuentra en cada receta de las doce semanas. Un hombro dolorido aparta los ejercicios afectados en todo el plan, no solo la primera semana." },
    { title: "Tu plan sigue aprendiendo", body: "Las cargas que anotas, las sesiones que te saltas, tu peso que cambia: el siguiente bloque se reconstruye sobre lo que realmente has hecho, no sobre lo previsto." },
    { title: "Un interlocutor a cualquier hora", body: "El coach IA retoma el método de tu coach para responder a las 23 h de un domingo, cuando una máquina está ocupada o una comida no encaja. Tu coach no tiene que estar despierto para eso." },
  ],
  engineLimit:
    "El motor no decide en lugar de tu coach: aplica su método. Y no sustituye ni una opinión médica, ni la mirada de un profesional sobre tu técnica.",
  navMethod: "El método",
  navPrograms: "Programas",
  navFaq: "Preguntas",
  leadPoints: [
    "Una semana completa, día a día",
    "Cargas objetivo e indicaciones técnicas",
    "Nutrición en cifras y lista de la compra",
    "Tabla de seguimiento para imprimir",
  ],
  leadReassure: "Sin compromiso, sin tarjeta bancaria",
  testimonialsTitle: "Lo que dicen sus clientes",
  leadChip: "Gratis",
  leadTitle: "Tu primera semana, gratis",
  heroLead: "Mi primera semana, gratis",
  leadBody: "Un plan real que seguir, calibrado sobre tu objetivo, tu nivel y tu material. Listo para imprimir.",
  leadCta: "Recibir mi programa",
  programsChip: "Programas",
  programsTitle: "Elige tu programa",
  noOffer: "Ninguna oferta disponible por ahora. Vuelve pronto.",
  giftTitle: "¿Ganas de regalar?",
  giftBody: "Regala un programa a alguien: tú pagas, la persona recibe un código para usar libremente.",
  giftCta: "Quiero regalar un programa",
  faqChip: "FAQ",
  faqTitle: "Preguntas frecuentes",
  faqs: [
    { q: "¿Hace falta un gimnasio o material especial?", a: "No. Fotografías lo que tienes, gimnasio completo, home gym o unas mancuernas, y el programa se construye únicamente con ese material." },
    { q: "Soy principiante, ¿es adecuado?", a: "Sí. El inicio del programa está dedicado a la técnica y a instalar el hábito. Después se progresa gradualmente." },
    { q: "¿Cómo funciona el pago?", a: "El pago es seguro con Stripe, directamente con tu coach. Según el programa elegido, es un pago único o una suscripción (mensual o anual), cancelable en cualquier momento desde tu espacio." },
    { q: "¿Quién diseña realmente el programa?", a: "Tu coach. El programa se construye sobre SU método; se apoya en una IA que ha entrenado con su forma de trabajar. El asistente IA prolonga ese acompañamiento en el día a día, pero no sustituye a tu coach ni a una opinión médica." },
    { q: "¿Tengo una lesión, una patología o un embarazo?", a: "Un filtro de salud al inicio detecta las situaciones de riesgo. El programa se adapta o se pone en pausa a la espera de la opinión de tu médico." },
    { q: "3 meses o 12 meses, ¿cuál es la diferencia?", a: "El de 3 meses es un sprint con línea de meta: 3 ciclos que suben de intensidad, para un resultado visible en 12 semanas. El de 12 meses es un programa que aprende de ti: 4 bloques de 3 meses, cada uno reconstruido sobre lo que realmente has hecho en el anterior, con una orientación que cambia a lo largo del año (bases, volumen, fuerza, pico)." },
    { q: "¿Qué pasa después del programa?", a: "El coach IA se desactiva al final, pero tu plan sigue consultable un tiempo más en solo lectura. En un 3 meses, tu coach te propone continuar con 12 meses descontando lo que ya has pagado." },
  ],
  finalTitle: "Tu transformación empieza hoy.",
  legalNote: "Acompañamiento deportivo y de bienestar, sin fines terapéuticos. El acompañamiento nutricional es una ayuda para elegir las comidas, no una prescripción dietética. No sustituye una opinión médica.",
  footerLogin: "Iniciar sesión",
  footerLegal: "Aviso legal",
  footerPrivacy: "Privacidad",
  footerTerms: "Condiciones",
  poweredBy: "Impulsado por",
  mostChosen: "El más elegido",
  oneTime: "pago único",
  perMonthOn: (amount, months) => `es decir, ${amount}/mes durante ${months} meses`,
  choose: "Elegir este programa",
  soon: "Próximamente",
  payOnce: "De una vez",
  payInstallments: (n) => `En ${n} plazos`,
  perMonthTimes: (n) => `/mes × ${n}`,
  autoStop: (n) => `${n} pagos, y luego nada más: la parada es automática.`,
  totalOver: (amount, n) => `es decir, ${amount} en total durante ${n} meses`,
  mockCoach: "Coach IA",
  mockCoachSub: "responde en directo",
  mockSession: "Sesión del día",
  mockDay: "Día 24",
};

export const GYM_ES: Overrides = {
  testimonialsTitle: "Lo que dicen sus socios",
  defaultTagline:
    "Un programa construido por el equipo de tu gimnasio, con las máquinas que están aquí, y que te sigue también los días que no vienes. Asistido por un motor especializado en transformación física.",
  heroChip: "Programa incluido en tu cuota",
  heroChecks: ["Construido sobre el material del gimnasio", "Seguido por el equipo", "También los días sin venir"],
  stats: [
    { v: "Nuestro equipo", l: "diseña tu programa" },
    { v: "Nuestras máquinas", l: "las que tienes a mano" },
    { v: "7 d / 7", l: "un plan incluso fuera del gimnasio" },
    { v: "Sin coste extra", l: "incluido en tu suscripción" },
  ],
  featuresTitle: "Lo que tu cuota te aporta de más",
  features: [
    { title: "El método del gimnasio", body: "Nuestros coaches han dejado constancia de su forma de hacer progresar: es ella la que construye tu plan, no un modelo genérico comprado en otro sitio." },
    { title: "Nuestras máquinas, no las de un catálogo", body: "El parque del gimnasio se conoce puesto por puesto. Tu programa nunca te manda a un aparato que no tenemos, ni al que siempre está ocupado a las 18 h." },
    { title: "Adaptado a ti, no al grupo", body: "Patologías, alergias, dieta, marco religioso, horarios: tu plan tiene en cuenta tu situación, no la media de los socios." },
    { title: "Un motor, no un piloto", body: "El equipo mantiene el control de cada decisión. El motor de IA le sirve para aplicar su método a cada socio sin dejar pasar nada." },
    { title: "Zonas cardíacas precisas", body: "Tus zonas de intensidad calculadas, para que el cardio del gimnasio sirva de verdad para algo." },
    { title: "Tu espacio de socio", body: "Sesiones interactivas, calendario, diario de cargas, diario alimentario por escaneo de código de barras, curva de peso: lo que haces aquí y en otros sitios, en el mismo lugar." },
    { title: "Herramientas de entrenamiento", body: "Temporizador de descanso, diario serie a serie, progresión visible: con qué entrenar solo sin perder el hilo." },
    { title: "Un interlocutor fuera del horario de apertura", body: "El coach IA retoma el método del gimnasio y responde cuando la recepción está cerrada, de viaje o de vacaciones." },
  ],
  gymChip: "Nuestro parque",
  gymTitle: "Nuestras máquinas ya están en tu programa.",
  gymBody:
    "Sabemos exactamente lo que contiene el gimnasio. Tu plan está escrito con ese material, y si entrenas en otro sitio durante una semana, fotografías el lugar y el programa se adapta.",
  gymBullets: ["La zona de peso libre", "Las máquinas guiadas", "El espacio cardio", "Y tu gimnasio de vacaciones, en foto"],
  spaceChip: "Espacio de socio",
  spaceTitle: "Tu programa te sigue fuera del gimnasio.",
  spaceBody:
    "La mayoría de los abandonos llegan las semanas en que no se viene. Tu espacio de socio te dice qué hacer ese día, en el gimnasio o en otro sitio, y guarda registro de lo que has hecho.",
  authorChip: "Quién diseña tu programa",
  authorTitle: "Los coaches del gimnasio. No un robot.",
  authorBody:
    "Los ejercicios, el orden de las sesiones, las cargas de partida, la velocidad de progresión: todo viene del método de nuestro equipo, de lo que ve funcionar aquí, en esta sala, con nuestros socios.",
  authorPoints: [
    { title: "Un método de la casa", body: "Nuestros coaches han escrito su forma de trabajar: sus principios, sus ejercicios de referencia, sus progresiones, lo que se niegan a hacer hacer. Tu programa se ajusta a ello." },
    { title: "Gente con la que te puedes cruzar", body: "No son programas comprados a un proveedor lejano. El equipo que los firma es el que ves en la sala." },
    { title: "Un relevo entre dos visitas", body: "Lo que un coach te ha corregido en sesión se encuentra en tu plan de la semana, en lugar de perderse." },
  ],
  authorSignature: (name) => `Programas firmados por el equipo ${name}`,
  engineBody:
    "Para aplicar su método a cada socio, el equipo se apoya en un motor de IA entrenado para una sola cosa: construir planes de entrenamiento y de nutrición. No es un asistente genérico al que se le pregunta el tiempo.",
  enginePoints: [
    { title: "Un plan a medida para cada socio", body: "Escribir a mano un programa personalizado por socio sería imposible a la escala de un gimnasio. El motor lo hace factible sin caer en el programa fotocopiado." },
    { title: "Nada se olvida por el camino", body: "Una alergia declarada en la inscripción se encuentra en cada receta de las doce semanas. Un hombro dolorido aparta los ejercicios afectados en todo el plan." },
    { title: "Tu plan sigue aprendiendo", body: "Las cargas que anotas, las sesiones que te saltas, tu peso que cambia: el siguiente bloque se reconstruye sobre lo que realmente has hecho." },
    { title: "Disponible cuando el gimnasio está cerrado", body: "El coach IA retoma el método del equipo para responder a las 23 h de un domingo, cuando una máquina está ocupada o una comida no encaja." },
  ],
  engineLimit:
    "El motor no decide en lugar de nuestros coaches: aplica su método. Y no sustituye ni una opinión médica, ni la mirada de un coach sobre tu técnica.",
  stepsTitle: "3 pasos, desde hoy",
  steps: [
    { k: "01", title: "Responde al cuestionario", body: "Objetivos, nivel, disponibilidad, salud, alergias y preferencias alimentarias. Diez minutos, una vez." },
    { k: "02", title: "Tu plan se construye sobre nuestro parque", body: "El material del gimnasio ya se conoce. Solo fotografías si entrenas en otro sitio." },
    { k: "03", title: "Entrena, aquí y en otros sitios", body: "Tu espacio de socio te dice qué hacer cada día, y anota lo que haces." },
  ],
  forWhoTitle: "¿Para qué socio?",
  forWho: [
    { title: "El que da vueltas en círculo", body: "Vienes regularmente pero repites las mismas máquinas desde hace meses. Te damos una progresión escrita." },
    { title: "El que acaba de llegar", body: "No sabes por dónde empezar en la sala. El plan te dice qué hacer, en qué orden, con qué carga." },
    { title: "El que se descuelga en invierno", body: "Las semanas en que no vienes ya no son semanas perdidas: el plan te sigue en casa." },
    { title: "El que tiene una restricción de salud", body: "Filtro de salud al inicio, ejercicios adaptados, validación médica si hace falta." },
    { title: "El que viaja", body: "Una foto del gimnasio del hotel basta para adaptar la semana." },
    { title: "El que quiere nutrición", body: "No solo el entrenamiento: calorías, macros y recetas que tienen en cuenta tus restricciones." },
  ],
  leadTitle: "Llévate una semana gratis",
  heroLead: "Una semana gratis, para empezar",
  leadBody: "Un plan real que seguir, calibrado sobre tu objetivo y sobre el material que tienes. Listo para imprimir.",
  programsTitle: "Nuestras fórmulas",
  finalTitle: "Tu gimnasio. Tu programa. Desde la próxima sesión.",
  giftTitle: "¿Ganas de regalar?",
  giftBody: "Regala un acompañamiento a alguien: tú pagas, la persona recibe un código para usar libremente.",
};
